import EnsembleCore
import SwiftUI

public struct TrackRow: View {
    let track: Track
    let showArtwork: Bool
    let showTrackNumber: Bool
    let isPlaying: Bool
    let isAutoGenerated: Bool
    let onTap: () -> Void
    let onPlayNext: (() -> Void)?
    let onPlayLast: (() -> Void)?
    let onAddToPlaylist: (() -> Void)?
    let onAddToRecentPlaylist: (() -> Void)?
    let onToggleFavorite: (() -> Void)?
    let onGoToAlbum: (() -> Void)?
    let onGoToArtist: (() -> Void)?
    let onShareLink: (() -> Void)?
    let onShareFile: (() -> Void)?
    let isFavorited: Bool?
    let recentPlaylistTitle: String?
    let supplementalMetadataWidth: CGFloat?
    @Environment(\.dependencies) private var deps
    @State private var isEditingMetadata = false
    @State private var isConfirmingDelete = false
    /// Cached per-track availability — only updated when this track's availability actually
    /// changes, instead of re-rendering all visible rows on every generation bump.
    @State private var cachedAvailability: TrackAvailability = .available

    public init(
        track: Track,
        showArtwork: Bool = true,
        showTrackNumber: Bool = false,
        isPlaying: Bool = false,
        isAutoGenerated: Bool = false,
        onPlayNext: (() -> Void)? = nil,
        onPlayLast: (() -> Void)? = nil,
        onAddToPlaylist: (() -> Void)? = nil,
        onAddToRecentPlaylist: (() -> Void)? = nil,
        onToggleFavorite: (() -> Void)? = nil,
        onGoToAlbum: (() -> Void)? = nil,
        onGoToArtist: (() -> Void)? = nil,
        onShareLink: (() -> Void)? = nil,
        onShareFile: (() -> Void)? = nil,
        isFavorited: Bool? = nil,
        recentPlaylistTitle: String? = nil,
        supplementalMetadataWidth: CGFloat? = nil,
        onTap: @escaping () -> Void
    ) {
        self.track = track
        self.showArtwork = showArtwork
        self.showTrackNumber = showTrackNumber
        self.isPlaying = isPlaying
        self.isAutoGenerated = isAutoGenerated
        self.onPlayNext = onPlayNext
        self.onPlayLast = onPlayLast
        self.onAddToPlaylist = onAddToPlaylist
        self.onAddToRecentPlaylist = onAddToRecentPlaylist
        self.onToggleFavorite = onToggleFavorite
        self.onGoToAlbum = onGoToAlbum
        self.onGoToArtist = onGoToArtist
        self.onShareLink = onShareLink
        self.onShareFile = onShareFile
        self.isFavorited = isFavorited
        self.recentPlaylistTitle = recentPlaylistTitle
        self.supplementalMetadataWidth = supplementalMetadataWidth
        self.onTap = onTap
    }

    public var body: some View {
        HStack(spacing: TrackListLayoutMetrics.rowInterItemSpacing) {
            Button(action: handleTap) {
                rowContentView
                    .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
            .frame(maxWidth: .infinity, alignment: .leading)

            if showsOverflowMenuButton {
                overflowMenuButton
            }
        }
        .contentShape(Rectangle())
        .opacity(isUnavailableOffline ? TrackListLayoutMetrics.unavailableOpacity : 1)
        .transition(isAutoGenerated ? .opacity : .identity)
        .contextMenu { contextMenuItems }
        .keyboardSafeEditorPresentation(isPresented: $isEditingMetadata) {
            MetadataEditSheet(kind: .track, currentTitle: track.title) { newTitle in
                do {
                    try await deps.metadataMutationService.editTrack(
                        track,
                        request: MetadataEditRequest(title: newTitle)
                    )
                    await MainActor.run {
                        deps.toastCenter.show(
                            ToastPayload(
                                style: .success,
                                iconSystemName: EnsembleDesign.Icon.checkmark,
                                title: "Track updated",
                                message: "\"\(newTitle)\" was saved to Plex.",
                                dedupeKey: "track-edit-\(track.id)"
                            )
                        )
                    }
                } catch {
                    await MainActor.run {
                        deps.toastCenter.show(
                            ToastPayload(
                                style: .error,
                                iconSystemName: EnsembleDesign.Icon.error,
                                title: "Couldn't edit track",
                                message: error.localizedDescription,
                                dedupeKey: "track-edit-failed-\(track.id)"
                            )
                        )
                    }
                    throw error
                }
            }
        }
        .confirmationDialog(
            "Delete Track?",
            isPresented: $isConfirmingDelete,
            titleVisibility: .visible
        ) {
            Button("Delete Track", role: .destructive) {
                Task {
                    do {
                        try await deps.metadataMutationService.deleteTrack(track)
                        await MainActor.run {
                            deps.toastCenter.show(
                                ToastPayload(
                                    style: .success,
                                    iconSystemName: EnsembleDesign.Icon.deleteFilled,
                                    title: "Track deleted",
                                    message: "\"\(track.title)\" was removed from Plex.",
                                    dedupeKey: "track-delete-\(track.id)"
                                )
                            )
                        }
                    } catch {
                        await MainActor.run {
                            deps.toastCenter.show(
                                ToastPayload(
                                    style: .error,
                                    iconSystemName: EnsembleDesign.Icon.error,
                                    title: "Couldn't delete track",
                                    message: error.localizedDescription,
                                    dedupeKey: "track-delete-failed-\(track.id)"
                                )
                            )
                        }
                    }
                }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("This permanently deletes \"\(track.title)\" from the Plex server and removes its local cache.")
        }
        #if !os(watchOS)
        // App-internal drags use media references; external drops request the
        // same prepared audio file used by the Share File action.
        .onDrag {
            MediaDragPayload.trackItemProvider(for: track, shareService: deps.shareService)
        }
        #endif
        // Update cached availability when generation bumps (network/server/download change).
        // Only assigns @State (triggering re-render) when this track's availability actually changed.
        .onReceive(DependencyContainer.shared.trackAvailabilityResolver.$availabilityGeneration) { _ in
            let resolver = DependencyContainer.shared.trackAvailabilityResolver
            let newAvailability = resolver.availability(for: track)
            if newAvailability != cachedAvailability {
                cachedAvailability = newAvailability
            }
        }
        .onAppear {
            cachedAvailability = DependencyContainer.shared.trackAvailabilityResolver.availability(for: track)
        }
    }

    // MARK: - Extracted Row Content

    /// The row's visual content, extracted so it can be reused as the context menu preview
    @ViewBuilder
    private var rowContentView: some View {
        HStack(spacing: TrackListLayoutMetrics.rowInterItemSpacing) {
            if showTrackNumber {
                trackNumberView
                    .frame(width: TrackListLayoutMetrics.trackNumberWidth)
            }

            if showArtwork {
                ArtworkView(track: track, size: .tiny, cornerRadius: ArtworkCornerRadius.square(for: .tiny))
            }

            VStack(alignment: .leading, spacing: TrackListLayoutMetrics.primarySecondaryTextSpacing) {
                HStack(spacing: TrackListLayoutMetrics.rowTightAccessoryGap) {
                    Text(track.title)
                        .font(EnsembleDesign.Typography.rowPrimary)
                        .foregroundColor(isPlaying ? EnsembleDesign.Color.accent : (isAutoGenerated ? EnsembleDesign.Color.generated : EnsembleDesign.Color.primaryText))
                        .lineLimit(1)

                    if isAutoGenerated {
                        Image(systemName: EnsembleDesign.Icon.generatedBadge)
                            .font(EnsembleDesign.Typography.rowSecondary)
                            .foregroundColor(EnsembleDesign.Color.generated)
                    }
                }

                if !showsArtistMetadataColumn, let artist = track.artistName {
                    Text(artist)
                        .font(EnsembleDesign.Typography.stateMessage)
                        .foregroundColor(EnsembleDesign.Color.secondaryText)
                        .lineLimit(1)
                }
            }
            .layoutPriority(1)
            .frame(maxWidth: .infinity, alignment: .leading)

            if showsArtistMetadataColumn {
                Text(track.artistName ?? "Unknown Artist")
                    .font(EnsembleDesign.Typography.rowPrimary)
                    .foregroundColor(EnsembleDesign.Color.secondaryText)
                    .lineLimit(1)
                    .frame(width: artistMetadataColumnWidth, alignment: .leading)
            }

            if showsAlbumMetadataColumn {
                Text(track.albumName ?? "Unknown Album")
                    .font(EnsembleDesign.Typography.rowPrimary)
                    .foregroundColor(EnsembleDesign.Color.secondaryText)
                    .lineLimit(1)
                    .frame(width: albumMetadataColumnWidth, alignment: .leading)
            }

            Spacer()

            if usesFixedAccessoryColumns {
                downloadStatusView
                    .frame(
                        width: TrackListLayoutMetrics.downloadIndicatorDimension,
                        height: TrackListLayoutMetrics.downloadIndicatorDimension
                    )

                durationText
                    .frame(width: TrackListLayoutMetrics.durationColumnWidth, alignment: .trailing)
            } else {
                downloadStatusView

                durationText
            }
        }
        .frame(
            maxWidth: .infinity,
            minHeight: TrackListLayoutMetrics.rowContentMinHeight,
            alignment: .leading
        )
        // Favorite heart centered between screen edge and first content element
        .overlay(alignment: .leading) {
            if effectiveIsFavorited {
                Image(systemName: EnsembleDesign.Icon.favoriteFilled)
                    .font(EnsembleDesign.Typography.rowSecondary)
                    .foregroundColor(EnsembleDesign.Color.favorite)
                    .offset(x: -TrackListLayoutMetrics.favoriteIndicatorCenterX)
            }
        }
    }

    private var overflowMenuButton: some View {
        Menu {
            contextMenuItems
        } label: {
            Image(systemName: EnsembleDesign.Icon.trackActions)
                .font(EnsembleDesign.Typography.overflowIcon)
                .foregroundColor(EnsembleDesign.Color.secondaryText)
                .frame(
                    width: TrackListLayoutMetrics.overflowControlDimension,
                    height: TrackListLayoutMetrics.overflowControlDimension
                )
                .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Track Actions")
    }

    private var showsOverflowMenuButton: Bool {
        #if os(iOS)
        true
        #else
        false
        #endif
    }

    // MARK: - Context Menu Items

    @ViewBuilder
    private var contextMenuItems: some View {
        SwiftUIMediaMenuRenderer(
            sections: MediaMenuCatalog.sections(
                for: .track,
                context: .library,
                availability: MediaMenuAvailability(
                    hasRecentPlaylist: onAddToRecentPlaylist != nil && recentPlaylistTitle != nil,
                    canAddToRecentPlaylist: true,
                    canGoToAlbum: onGoToAlbum != nil && track.albumRatingKey != nil,
                    canGoToArtist: onGoToArtist != nil && track.artistRatingKey != nil,
                    canShareLink: onShareLink != nil,
                    canShareAudioFile: onShareFile != nil,
                    canFavorite: onToggleFavorite != nil,
                    canDownload: false,
                    canPin: false,
                    canEditMetadata: true,
                    canDelete: true,
                    canRename: false,
                    canEditPlaylist: false,
                    canRemoveFromQueue: false
                )
            ),
            state: MediaMenuState(
                recentPlaylistTitle: recentPlaylistTitle,
                isFavorited: effectiveIsFavorited
            ),
            handlers: MediaMenuHandlers(
                playNext: onPlayNext,
                playLast: onPlayLast,
                addToRecentPlaylist: onAddToRecentPlaylist,
                addToPlaylist: onAddToPlaylist,
                goToAlbum: onGoToAlbum,
                goToArtist: onGoToArtist,
                editMetadata: {
                    // Context-menu initiated editor presentation can be swallowed
                    // when triggered before the menu dismiss animation completes.
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) {
                        DispatchQueue.main.async {
                            isEditingMetadata = true
                        }
                    }
                },
                favorite: onToggleFavorite,
                shareLink: onShareLink,
                shareAudioFile: onShareFile,
                deleteTrack: {
                    isConfirmingDelete = true
                }
            )
        )
    }

    /// Whether this track is currently queued or actively downloading.
    private var isActivelyDownloading: Bool {
        deps.offlineDownloadService.activeDownloadRatingKeys.contains(track.id)
    }

    private var isUnavailableOffline: Bool {
        cachedAvailability.shouldDim
    }

    private func handleTap() {
        let availability = cachedAvailability
        guard availability.canPlay else {
            deps.toastCenter.show(
                ToastPayload(
                    style: .warning,
                    iconSystemName: EnsembleDesign.Icon.offline,
                    title: availability.userMessage ?? "Not available offline",
                    message: "Download this track before going offline.",
                    dedupeKey: "offline-track-blocked-\(track.id)"
                )
            )
            return
        }
        onTap()
    }

    private var effectiveIsFavorited: Bool {
        isFavorited ?? (track.rating >= 8)
    }

    private var showsArtistMetadataColumn: Bool {
        guard let supplementalMetadataWidth else { return false }
        return TrackListLayoutMetrics.showsArtistMetadataColumn(for: supplementalMetadataWidth)
    }

    private var showsAlbumMetadataColumn: Bool {
        guard let supplementalMetadataWidth else { return false }
        return TrackListLayoutMetrics.showsAlbumMetadataColumn(for: supplementalMetadataWidth)
    }

    private var usesFixedAccessoryColumns: Bool {
        showsArtistMetadataColumn || showsAlbumMetadataColumn
    }

    private var artistMetadataColumnWidth: CGFloat {
        TrackListLayoutMetrics.artistMetadataColumnWidth(for: supplementalMetadataWidth)
    }

    private var albumMetadataColumnWidth: CGFloat {
        TrackListLayoutMetrics.albumMetadataColumnWidth(for: supplementalMetadataWidth)
    }

    @ViewBuilder
    private var downloadStatusView: some View {
        if isActivelyDownloading {
            ProgressView()
                .scaleEffect(TrackListLayoutMetrics.downloadIndicatorScale)
                .frame(
                    width: TrackListLayoutMetrics.downloadIndicatorDimension,
                    height: TrackListLayoutMetrics.downloadIndicatorDimension
                )
        } else if track.isDownloaded {
            Image(systemName: EnsembleDesign.Icon.downloaded)
                .font(EnsembleDesign.Typography.rowSecondary)
                .foregroundColor(EnsembleDesign.Color.secondaryText)
                .frame(
                    width: TrackListLayoutMetrics.downloadIndicatorDimension,
                    height: TrackListLayoutMetrics.downloadIndicatorDimension
                )
        } else if usesFixedAccessoryColumns {
            Color.clear
                .frame(
                    width: TrackListLayoutMetrics.downloadIndicatorDimension,
                    height: TrackListLayoutMetrics.downloadIndicatorDimension
                )
        }
    }

    private var durationText: some View {
        Text(track.formattedDuration)
            .font(EnsembleDesign.Typography.stateMessage)
            .foregroundColor(EnsembleDesign.Color.secondaryText)
            .monospacedDigit()
    }

    @ViewBuilder
    private var trackNumberView: some View {
        if isPlaying {
            Image(systemName: EnsembleDesign.Icon.speakerPlaying)
                .font(EnsembleDesign.Typography.rowSecondary)
                .foregroundColor(EnsembleDesign.Color.accent)
        } else {
            Text("\(track.trackNumber)")
                .font(EnsembleDesign.Typography.stateMessage)
                .foregroundColor(EnsembleDesign.Color.secondaryText)
                .monospacedDigit()
        }
    }
}

// MARK: - Track List

public struct TrackListView: View {
    let tracks: [Track]
    let showArtwork: Bool
    let showTrackNumbers: Bool
    let currentTrackId: String?
    let autoGeneratedTrackIds: Set<String>
    let onTrackTap: (Track, Int) -> Void
    let onPlayNext: ((Track) -> Void)?
    let onPlayLast: ((Track) -> Void)?
    let onAddToPlaylist: ((Track) -> Void)?
    let onAddToRecentPlaylist: ((Track) -> Void)?
    let onToggleFavorite: ((Track) -> Void)?
    let onGoToAlbum: ((Track) -> Void)?
    let onGoToArtist: ((Track) -> Void)?
    let onShareLink: ((Track) -> Void)?
    let onShareFile: ((Track) -> Void)?
    let canAddToRecentPlaylist: ((Track) -> Bool)?
    let recentPlaylistTitle: String?
    let nowPlayingVM: NowPlayingViewModel?
    private let interactionModel: TrackRowInteractionModel
    @State private var supplementalMetadataWidth: CGFloat = 0

    public init(
        tracks: [Track],
        showArtwork: Bool = true,
        showTrackNumbers: Bool = false,
        currentTrackId: String? = nil,
        autoGeneratedTrackIds: Set<String> = [],
        onPlayNext: ((Track) -> Void)? = nil,
        onPlayLast: ((Track) -> Void)? = nil,
        onAddToPlaylist: ((Track) -> Void)? = nil,
        onAddToRecentPlaylist: ((Track) -> Void)? = nil,
        onToggleFavorite: ((Track) -> Void)? = nil,
        onGoToAlbum: ((Track) -> Void)? = nil,
        onGoToArtist: ((Track) -> Void)? = nil,
        onShareLink: ((Track) -> Void)? = nil,
        onShareFile: ((Track) -> Void)? = nil,
        canAddToRecentPlaylist: ((Track) -> Bool)? = nil,
        recentPlaylistTitle: String? = nil,
        nowPlayingVM: NowPlayingViewModel? = nil,
        onTrackTap: @escaping (Track, Int) -> Void
    ) {
        self.tracks = tracks
        self.showArtwork = showArtwork
        self.showTrackNumbers = showTrackNumbers
        self.currentTrackId = currentTrackId
        self.autoGeneratedTrackIds = autoGeneratedTrackIds
        self.onPlayNext = onPlayNext
        self.onPlayLast = onPlayLast
        self.onAddToPlaylist = onAddToPlaylist
        self.onAddToRecentPlaylist = onAddToRecentPlaylist
        self.onToggleFavorite = onToggleFavorite
        self.onGoToAlbum = onGoToAlbum
        self.onGoToArtist = onGoToArtist
        self.onShareLink = onShareLink
        self.onShareFile = onShareFile
        self.canAddToRecentPlaylist = canAddToRecentPlaylist
        self.recentPlaylistTitle = recentPlaylistTitle
        self.nowPlayingVM = nowPlayingVM
        self.onTrackTap = onTrackTap
        self.interactionModel = TrackRowInteractionModel(
            onPlayNext: onPlayNext,
            onPlayLast: onPlayLast,
            onAddToPlaylist: onAddToPlaylist,
            onAddToRecentPlaylist: onAddToRecentPlaylist,
            onToggleFavorite: onToggleFavorite,
            onGoToAlbum: onGoToAlbum,
            onGoToArtist: onGoToArtist,
            onShareLink: onShareLink,
            onShareFile: onShareFile,
            isTrackFavorited: nowPlayingVM.map { viewModel in { viewModel.isTrackFavorited($0) } },
            canAddToRecentPlaylist: canAddToRecentPlaylist,
            recentPlaylistTitle: recentPlaylistTitle
        )
    }

    public var body: some View {
        LazyVStack(spacing: EnsembleDesign.Spacing.none) {
            ForEach(Array(tracks.enumerated()), id: \.element.id) { index, track in
                let resolvedActions = interactionModel.resolve(for: track)
                let row = TrackRow(
                    track: track,
                    showArtwork: showArtwork,
                    showTrackNumber: showTrackNumbers,
                    isPlaying: track.id == currentTrackId,
                    isAutoGenerated: autoGeneratedTrackIds.contains(track.id),
                    onPlayNext: resolvedActions.onPlayNext,
                    onPlayLast: resolvedActions.onPlayLast,
                    onAddToPlaylist: resolvedActions.onAddToPlaylist,
                    onAddToRecentPlaylist: resolvedActions.onAddToRecentPlaylist,
                    onToggleFavorite: resolvedActions.onToggleFavorite,
                    onGoToAlbum: resolvedActions.onGoToAlbum,
                    onGoToArtist: resolvedActions.onGoToArtist,
                    onShareLink: resolvedActions.onShareLink,
                    onShareFile: resolvedActions.onShareFile,
                    isFavorited: resolvedActions.isFavorited,
                    recentPlaylistTitle: resolvedActions.recentPlaylistTitle,
                    supplementalMetadataWidth: supplementalMetadataWidth
                ) {
                    onTrackTap(track, index)
                }

                Group {
                    if let nowPlayingVM {
                        TrackSwipeContainer(
                            track: track,
                            nowPlayingVM: nowPlayingVM,
                            onPlayNext: resolvedActions.onPlayNext,
                            onPlayLast: resolvedActions.onPlayLast,
                            onAddToPlaylist: resolvedActions.onAddToPlaylist
                        ) {
                            row
                        }
                    } else {
                        row
                    }
                }
                .padding(.horizontal, TrackListLayoutMetrics.rowHorizontalPadding)
                .padding(.vertical, TrackListLayoutMetrics.rowVerticalPadding)

                if index < tracks.count - 1 {
                    TrackListDivider(
                        showArtwork: showArtwork,
                        showTrackNumbers: showTrackNumbers
                    )
                }
            }
        }
        .background(
            GeometryReader { geometry in
                Color.clear
                    .onAppear {
                        updateSupplementalMetadataWidth(geometry.size.width)
                    }
                    .onChange(of: geometry.size.width) { newWidth in
                        updateSupplementalMetadataWidth(newWidth)
                    }
            }
        )
    }

    private func updateSupplementalMetadataWidth(_ newWidth: CGFloat) {
        if abs(supplementalMetadataWidth - newWidth) > 1 {
            supplementalMetadataWidth = newWidth
        }
    }
}

struct TrackListDivider: View {
    let showArtwork: Bool
    let showTrackNumbers: Bool

    var body: some View {
        Divider()
            .overlay(TrackListLayoutMetrics.dividerColor)
            .padding(
                .leading,
                TrackListLayoutMetrics.contentLeadingInset(
                    showArtwork: showArtwork,
                    showTrackNumbers: showTrackNumbers
                )
            )
    }
}
