import EnsembleCore
import SwiftUI

public struct MoodTracksView: View {
    let mood: Mood
    @ObservedObject var nowPlayingVM: NowPlayingViewModel
    @StateObject private var viewModel: SearchViewModel
    @State private var moodTracks: [Track] = []
    @State private var isLoading = true
    @State private var error: String?

    public init(mood: Mood, nowPlayingVM: NowPlayingViewModel) {
        self.mood = mood
        self.nowPlayingVM = nowPlayingVM
        self._viewModel = StateObject(wrappedValue: DependencyContainer.shared.makeSearchViewModel())
    }

    public var body: some View {
        ZStack {
            if isLoading {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else if let error = error {
                VStack(spacing: 12) {
                    Text("Failed to load tracks")
                        .font(.headline)
                    Text(error)
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Button("Retry") {
                        Task {
                            await loadTracks()
                        }
                    }
                    .buttonStyle(.bordered)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.systemBackground))
            } else if moodTracks.isEmpty {
                VStack(spacing: 12) {
                    Image(systemName: "music.note")
                        .font(.system(size: 40))
                        .foregroundColor(.secondary)
                    Text("No tracks found")
                        .font(.headline)
                    Text("for \"\(mood.title)\"")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.systemBackground))
            } else {
                List {
                    ForEach(Array(moodTracks.enumerated()), id: \.element.id) { index, track in
                        TrackRow(
                            track: track,
                            isAutoGenerated: nowPlayingVM.isTrackAutoGenerated(track.id),
                            onTap: {
                                nowPlayingVM.play(tracks: moodTracks, startingAt: index)
                            }
                        )
                    }
                }
                .listStyle(.plain)
            }
        }
        .navigationTitle(mood.title)
        .navigationBarTitleDisplayMode(.inline)
        .task {
            await loadTracks()
        }
    }

    private func loadTracks() async {
        isLoading = true
        error = nil

        do {
            // Parse source composite key to get library info
            // Format: accountId:serverId:libraryKey
            guard let sourceKey = mood.sourceCompositeKey else {
                error = "Mood missing source information"
                isLoading = false
                return
            }
            
            let components = sourceKey.split(separator: ":")
            guard components.count >= 3 else {
                error = "Invalid mood source format: \(sourceKey)"
                isLoading = false
                return
            }
            
            let accountId = String(components[0])
            let serverId = String(components[1])
            let libraryId = String(components[2])

            // Get API client from dependency container
            guard let apiClient = DependencyContainer.shared.accountManager.makeAPIClient(accountId: accountId, serverId: serverId) else {
                error = "Server \(serverId) not available"
                isLoading = false
                return
            }
            
            // Fetch tracks for this mood
            let plexTracks = try await apiClient.getTracksByMood(sectionKey: libraryId, moodKey: mood.key)
            
            moodTracks = plexTracks.map { Track(from: $0) }
            
            if moodTracks.isEmpty {
                error = "No tracks found for '\(mood.title)' (got \(plexTracks.count) from API)"
            }
        } catch {
            self.error = "Failed to load tracks: \(error.localizedDescription)"
        }

        isLoading = false
    }
}
