import EnsembleCore
import SwiftUI

public struct MoodTracksView: View {
    let mood: Mood
    @ObservedObject var nowPlayingVM: NowPlayingViewModel
    @StateObject private var viewModel: SearchViewModel
    @State private var moodTracks: [Track] = []
    @State private var isLoading = true
    @State private var error: String?

    public init(mood: Mood, nowPlayingVM: NowPlayingViewModel) {
        self.mood = mood
        self.nowPlayingVM = nowPlayingVM
        self._viewModel = StateObject(wrappedValue: DependencyContainer.shared.makeSearchViewModel())
    }

    public var body: some View {
        ZStack {
            if isLoading {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else if let error = error {
                VStack(spacing: 12) {
                    Text("Failed to load tracks")
                        .font(.headline)
                    Text(error)
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Button("Retry") {
                        Task {
                            await loadTracks()
                        }
                    }
                    .buttonStyle(.bordered)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.systemBackground))
            } else if moodTracks.isEmpty {
                VStack(spacing: 12) {
                    Image(systemName: "music.note")
                        .font(.system(size: 40))
                        .foregroundColor(.secondary)
                    Text("No tracks found")
                        .font(.headline)
                    Text("for \"\(mood.title)\"")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.systemBackground))
            } else {
                ScrollView {
                    VStack(spacing: 20) {
                        // Mood card
                        moodCardView
                        
                        // Play and Shuffle buttons
                        HStack(spacing: 12) {
                            Button(action: {
                                if !nowPlayingVM.isAutoplayEnabled {
                                    nowPlayingVM.toggleAutoplay()
                                }
                                if nowPlayingVM.isShuffleEnabled {
                                    nowPlayingVM.toggleShuffle()
                                }
                                nowPlayingVM.play(tracks: moodTracks, startingAt: 0)
                            }) {
                                HStack {
                                    Image(systemName: "play.fill")
                                    Text("Play")
                                }
                                .frame(maxWidth: .infinity)
                                .padding(.vertical, 12)
                                .background(Color.accentColor)
                                .foregroundColor(.white)
                                .cornerRadius(8)
                            }
                            
                            Button(action: {
                                if !nowPlayingVM.isAutoplayEnabled {
                                    nowPlayingVM.toggleAutoplay()
                                }
                                if !nowPlayingVM.isShuffleEnabled {
                                    nowPlayingVM.toggleShuffle()
                                }
                                nowPlayingVM.play(tracks: moodTracks, startingAt: 0)
                            }) {
                                HStack {
                                    Image(systemName: "shuffle")
                                    Text("Shuffle")
                                }
                                .frame(maxWidth: .infinity)
                                .padding(.vertical, 12)
                                .background(Color.accentColor)
                                .foregroundColor(.white)
                                .cornerRadius(8)
                            }
                        }
                        .padding(.horizontal)
                        
                        // Tracks
                        VStack(spacing: 0) {
                            ForEach(Array(moodTracks.enumerated()), id: \.element.id) { index, track in
                                TrackRow(
                                    track: track,
                                    isAutoGenerated: nowPlayingVM.isTrackAutoGenerated(track.id),
                                    onPlayNext: { nowPlayingVM.playNext(track) },
                                    onPlayLast: { nowPlayingVM.playLast(track) },
                                    onTap: {
                                        if !nowPlayingVM.isAutoplayEnabled {
                                            nowPlayingVM.toggleAutoplay()
                                        }
                                        nowPlayingVM.play(tracks: moodTracks, startingAt: index)
                                    }
                                )
                                
                                if index < moodTracks.count - 1 {
                                    Divider()
                                }
                            }
                        }
                        .padding(.horizontal)
                    }
                    .padding(.vertical)
                }
            }
        }
        .navigationTitle(mood.title)
        .navigationBarTitleDisplayMode(.inline)
        .task {
            await loadTracks()
        }
    }
    
    // MARK: - Mood Card
    
    private var moodCardView: some View {
        VStack(spacing: 8) {
            // Gradient background with music icon
            ZStack {
                LinearGradient(
                    colors: [
                        moodColor.opacity(0.8),
                        moodColor.opacity(0.4)
                    ],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
                
                Image(systemName: "music.note.list")
                    .font(.system(size: 40))
                    .foregroundColor(.white.opacity(0.9))
            }
            .frame(height: 140)
            .cornerRadius(8)
            .shadow(color: Color.black.opacity(0.15), radius: 6, x: 0, y: 2)
            
            // Mood title
            Text(mood.title)
                .font(.title2)
                .fontWeight(.bold)
                .foregroundColor(.primary)
        }
        .padding(.horizontal)
    }
    
    // MARK: - Helpers
    
    /// Generate a deterministic color based on mood name
    private var moodColor: Color {
        let colors: [Color] = [
            .blue, .purple, .pink, .red, .orange, .yellow, .green, .teal, .indigo
        ]
        
        let hash = mood.title.utf8.reduce(0) { ($0 &* 31) &+ Int($1) }
        return colors[abs(hash) % colors.count]
    }

    private func loadTracks() async {
        isLoading = true
        error = nil

        var allTracks: [Track] = []
        var trackMap: [String: Track] = [:]  // For deduplication by ratingKey
        
        // Fetch mood tracks from all enabled libraries
        let accountManager = DependencyContainer.shared.accountManager
        
        for account in accountManager.plexAccounts {
            for server in account.servers {
                guard let client = accountManager.makeAPIClient(accountId: account.id, serverId: server.id) else {
                    continue
                }
                
                let enabledLibraries = server.libraries.filter { $0.isEnabled }
                for library in enabledLibraries {
                    do {
                        let plexTracks = try await client.getTracksByMood(sectionKey: library.key, moodKey: mood.key)
                        
                        // Create composite key for this track from this library
                        let sourceKey = "plex:\(account.id):\(server.id):\(library.key)"
                        
                        for plexTrack in plexTracks {
                            // Create track with explicit sourceKey including plex: prefix
                            let track = Track(from: plexTrack, sourceKey: sourceKey)
                            
                            // Dedup by ratingKey - keep first occurrence
                            if trackMap[track.id] == nil {
                                trackMap[track.id] = track
                                allTracks.append(track)
                            }
                        }
                    } catch {
                        // Continue to next library if this one fails
                        continue
                    }
                }
            }
        }
        
        moodTracks = allTracks
        
        if moodTracks.isEmpty {
            error = "No tracks found for '\(mood.title)'"
        }

        isLoading = false
    }
}
