import EnsembleCore
import SwiftUI

public struct MoodTracksView: View {
    let mood: Mood
    @ObservedObject var nowPlayingVM: NowPlayingViewModel
    @StateObject private var viewModel: SearchViewModel
    @State private var moodTracks: [Track] = []
    @State private var isLoading = true
    @State private var error: String?

    public init(mood: Mood, nowPlayingVM: NowPlayingViewModel) {
        self.mood = mood
        self.nowPlayingVM = nowPlayingVM
        self._viewModel = StateObject(wrappedValue: DependencyContainer.shared.makeSearchViewModel())
    }

    public var body: some View {
        ZStack {
            if isLoading {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else if let error = error {
                VStack(spacing: 12) {
                    Text("Failed to load tracks")
                        .font(.headline)
                    Text(error)
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Button("Retry") {
                        Task {
                            await loadTracks()
                        }
                    }
                    .buttonStyle(.bordered)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.systemBackground))
            } else if moodTracks.isEmpty {
                VStack(spacing: 12) {
                    Image(systemName: "music.note")
                        .font(.system(size: 40))
                        .foregroundColor(.secondary)
                    Text("No tracks found")
                        .font(.headline)
                    Text("for \"\(mood.title)\"")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.systemBackground))
            } else {
                ZStack(alignment: .top) {
                    // Full-bleed background gradient
                    backgroundGradient
                        .ignoresSafeArea()

                    ScrollView {
                        VStack(spacing: 0) {
                            // Header with mood icon and title
                            headerView

                            // Play and Shuffle buttons
                            actionButtons

                            // Tracks
                            VStack(spacing: 0) {
                                ForEach(Array(moodTracks.enumerated()), id: \.element.id) { index, track in
                                    TrackRow(
                                        track: track,
                                        isAutoGenerated: nowPlayingVM.isTrackAutoGenerated(track.id),
                                        onPlayNext: { nowPlayingVM.playNext(track) },
                                        onPlayLast: { nowPlayingVM.playLast(track) },
                                        onTap: {
                                            if !nowPlayingVM.isAutoplayEnabled {
                                                nowPlayingVM.toggleAutoplay()
                                            }
                                            nowPlayingVM.play(tracks: moodTracks, startingAt: index)
                                        }
                                    )
                                    .padding(.horizontal)
                                    .padding(.vertical, 8)

                                    if index < moodTracks.count - 1 {
                                        Divider().padding(.leading, 16)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        .safeAreaInset(edge: .bottom) {
            Color.clear.frame(height: 140)
        }
        .navigationTitle(mood.title)
        .navigationBarTitleDisplayMode(.inline)
        .task {
            await loadTracks()
        }
    }
    
    // MARK: - Header Views

    private var backgroundGradient: some View {
        LinearGradient(
            colors: [
                moodColor.opacity(0.6),
                moodColor.opacity(0.3)
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
        .mask(
            LinearGradient(
                colors: [.white, .clear],
                startPoint: .top,
                endPoint: .bottom
            )
        )
        .frame(height: 400)
    }

    private var headerView: some View {
        VStack(spacing: 16) {
            // Centered mood icon
            ZStack {
                Circle()
                    .fill(moodColor.opacity(0.2))
                    .frame(width: 140, height: 140)

                Image(systemName: "music.note.list")
                    .font(.system(size: 60))
                    .foregroundColor(moodColor)
            }
            .shadow(color: Color.black.opacity(0.1), radius: 10, x: 0, y: 5)

            // Mood title
            Text(mood.title)
                .font(.title2)
                .fontWeight(.bold)
                .multilineTextAlignment(.center)
        }
        .padding()
    }

    private var actionButtons: some View {
        HStack(spacing: 12) {
            Button(action: {
                if !nowPlayingVM.isAutoplayEnabled {
                    nowPlayingVM.toggleAutoplay()
                }
                if nowPlayingVM.isShuffleEnabled {
                    nowPlayingVM.toggleShuffle()
                }
                nowPlayingVM.play(tracks: moodTracks, startingAt: 0)
            }) {
                HStack {
                    Image(systemName: "play.fill")
                    Text("Play")
                }
                .font(.headline)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 12)
                .background(Color.accentColor)
                .foregroundColor(.white)
                .cornerRadius(10)
            }

            Button(action: {
                if !nowPlayingVM.isAutoplayEnabled {
                    nowPlayingVM.toggleAutoplay()
                }
                if !nowPlayingVM.isShuffleEnabled {
                    nowPlayingVM.toggleShuffle()
                }
                nowPlayingVM.play(tracks: moodTracks, startingAt: 0)
            }) {
                HStack {
                    Image(systemName: "shuffle")
                    Text("Shuffle")
                }
                .font(.headline)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 12)
                .background(Color.gray.opacity(0.2))
                .foregroundColor(.primary)
                .cornerRadius(10)
            }
        }
        .padding(.horizontal)
        .padding(.bottom)
    }
    
    // MARK: - Helpers
    
    /// Generate a deterministic color based on mood name
    private var moodColor: Color {
        let colors: [Color] = [
            .blue, .purple, .pink, .red, .orange, .yellow, .green, .teal, .indigo
        ]
        
        let hash = mood.title.utf8.reduce(0) { ($0 &* 31) &+ Int($1) }
        return colors[abs(hash) % colors.count]
    }

    private func loadTracks() async {
        isLoading = true
        error = nil

        var allTracks: [Track] = []
        var trackMap: [String: Track] = [:]  // For deduplication by ratingKey
        
        // Fetch mood tracks from all enabled libraries
        let accountManager = DependencyContainer.shared.accountManager
        
        for account in accountManager.plexAccounts {
            for server in account.servers {
                guard let client = accountManager.makeAPIClient(accountId: account.id, serverId: server.id) else {
                    continue
                }
                
                let enabledLibraries = server.libraries.filter { $0.isEnabled }
                for library in enabledLibraries {
                    do {
                        let plexTracks = try await client.getTracksByMood(sectionKey: library.key, moodKey: mood.key)
                        
                        // Create composite key for this track from this library
                        let sourceKey = "plex:\(account.id):\(server.id):\(library.key)"
                        
                        for plexTrack in plexTracks {
                            // Create track with explicit sourceKey including plex: prefix
                            let track = Track(from: plexTrack, sourceKey: sourceKey)
                            
                            // Dedup by ratingKey - keep first occurrence
                            if trackMap[track.id] == nil {
                                trackMap[track.id] = track
                                allTracks.append(track)
                            }
                        }
                    } catch {
                        // Continue to next library if this one fails
                        continue
                    }
                }
            }
        }
        
        moodTracks = allTracks
        
        if moodTracks.isEmpty {
            error = "No tracks found for '\(mood.title)'"
        }

        isLoading = false
    }
}
