import Foundation

struct PlaybackQueueDownloadRefreshResult: Equatable {
    let changedTrackIds: Set<String>
    let nonCurrentTrackIdsNeedingCacheEviction: Set<String>

    var changed: Bool {
        !changedTrackIds.isEmpty
    }
}

/// Owns queue snapshot persistence plus lightweight queue/history mutations that
/// do not need access to playback launch or engine state.
final class PlaybackQueueController {
    private let queueStore: PlaybackQueueStore
    private let maxHistorySize: Int
    private var legacyAutoGeneratedTrackIds: Set<String> = []

    init(queueStore: PlaybackQueueStore, maxHistorySize: Int) {
        self.queueStore = queueStore
        self.maxHistorySize = maxHistorySize
    }

    func recordToHistory(_ item: QueueItem, playbackHistory: inout [QueueItem]) {
        var historyItem = item
        if historyItem.source == .autoplay || historyItem.source == .upNext {
            historyItem.source = .continuePlaying
        }

        guard playbackHistory.last?.track.playbackIdentity != item.track.playbackIdentity else { return }
        playbackHistory.append(historyItem)
        if playbackHistory.count > maxHistorySize {
            playbackHistory.removeFirst()
        }
    }

    func flattenAutoplayItemsBeforeIndex(
        _ index: Int,
        currentQueueIndex: Int,
        queue: inout [QueueItem]
    ) {
        let start = currentQueueIndex + 1
        guard start < queue.count else { return }

        for i in start ..< min(index, queue.count) where queue[i].source == .autoplay {
            queue[i].source = .continuePlaying
        }
    }

    func clearAutoGeneratedTrackIds() {
        legacyAutoGeneratedTrackIds.removeAll()
    }

    func replaceAutoGeneratedTrackIds(with trackIds: Set<String>) {
        legacyAutoGeneratedTrackIds = trackIds
    }

    func syncAutoGeneratedTrackIds(from queue: [QueueItem]) {
        legacyAutoGeneratedTrackIds = Set(queue.filter { $0.source == .autoplay }.map(\.track.playbackIdentity))
    }

    func markAutoGeneratedTrack(id: String) {
        legacyAutoGeneratedTrackIds.insert(id)
    }

    @discardableResult
    func removeAutoGeneratedTrack(id: String) -> Bool {
        legacyAutoGeneratedTrackIds.remove(id) != nil
    }

    func isTrackAutoGenerated(id trackId: String, queue: [QueueItem]) -> Bool {
        queue.contains { $0.track.playbackIdentity == trackId && $0.source == .autoplay }
            || legacyAutoGeneratedTrackIds.contains(trackId)
    }

    @discardableResult
    func updateStreamingQuality(
        _ quality: String,
        queue: inout [QueueItem],
        existingLocalFilePaths: Set<String>? = nil,
        fileExists: (String) -> Bool = { FileManager.default.fileExists(atPath: $0) }
    ) -> Bool {
        var changed = false
        for i in queue.indices {
            if let path = queue[i].track.localFilePath,
               existingLocalFilePaths?.contains(path) ?? fileExists(path) {
                continue
            }
            if queue[i].streamingQuality != quality {
                queue[i].streamingQuality = quality
                changed = true
            }
        }
        return changed
    }

    func refreshDownloadState(
        queue: inout [QueueItem],
        currentQueueIndex: Int,
        fallbackStreamingQuality: String,
        localFilePathForTrack: (Track) async -> String?
    ) async -> PlaybackQueueDownloadRefreshResult {
        var changedTrackIds = Set<String>()
        var nonCurrentTrackIdsNeedingCacheEviction = Set<String>()

        for i in queue.indices {
            let track = queue[i].track
            let currentPath = await localFilePathForTrack(track)
            guard track.localFilePath != currentPath else { continue }

            queue[i] = QueueItem(
                id: queue[i].id,
                track: track.withLocalFilePath(currentPath),
                source: queue[i].source,
                streamingQuality: currentPath == nil ? fallbackStreamingQuality : nil
            )
            changedTrackIds.insert(track.playbackIdentity)

            if i != currentQueueIndex {
                nonCurrentTrackIdsNeedingCacheEviction.insert(track.playbackIdentity)
            }
        }

        return PlaybackQueueDownloadRefreshResult(
            changedTrackIds: changedTrackIds,
            nonCurrentTrackIdsNeedingCacheEviction: nonCurrentTrackIdsNeedingCacheEviction
        )
    }

    func saveSnapshot(
        queue: [QueueItem],
        history: [QueueItem],
        currentIndex: Int,
        currentTime: TimeInterval
    ) {
        queueStore.save(
            queue: queue,
            history: history,
            currentIndex: currentIndex,
            currentTime: currentTime
        )
    }

    func loadSnapshot() -> PlaybackQueueSnapshot? {
        queueStore.load()
    }
}
