import Foundation
import EnsembleDomain

struct PlaybackQueueDownloadRefreshResult: Equatable {
    let changedTrackIds: Set<String>
    let nonCurrentTrackIdsNeedingCacheEviction: Set<String>

    var changed: Bool {
        !changedTrackIds.isEmpty
    }
}

struct PlaybackQueueMoveResult: Equatable {
    let item: QueueItem
    let destinationIndex: Int
}

enum PlaybackPreviousNavigationTarget: Equatable {
    case seekToZero
    case queueIndex(Int)
    case historyIndex(Int)
}

struct PlaybackFutureAutoplayPruneResult: Equatable {
    let queue: [QueueItem]
    let removedTrackIds: Set<String>
    let removedItemCount: Int
}

/// Owns queue snapshot persistence plus lightweight queue/history mutations that
/// do not need access to playback launch or engine state.
final class PlaybackQueueController {
    private let queueStore: PlaybackQueueStore
    private let maxHistorySize: Int
    private var legacyAutoGeneratedTrackIds: Set<String> = []

    init(queueStore: PlaybackQueueStore, maxHistorySize: Int) {
        self.queueStore = queueStore
        self.maxHistorySize = maxHistorySize
    }

    func recordToHistory(_ item: QueueItem, playbackHistory: inout [QueueItem]) {
        var historyItem = item
        if historyItem.source == .autoplay || historyItem.source == .upNext {
            historyItem.source = .continuePlaying
        }

        guard playbackHistory.last?.track.playbackIdentity != item.track.playbackIdentity else { return }
        playbackHistory.append(historyItem)
        if playbackHistory.count > maxHistorySize {
            playbackHistory.removeFirst()
        }
    }

    func recordCurrentAndSkippedItems(
        before targetIndex: Int,
        queue: [QueueItem],
        currentQueueIndex: Int,
        playbackHistory: inout [QueueItem]
    ) {
        guard queue.indices.contains(currentQueueIndex) else { return }
        recordToHistory(queue[currentQueueIndex], playbackHistory: &playbackHistory)

        guard targetIndex > currentQueueIndex + 1 else { return }
        for index in (currentQueueIndex + 1) ..< targetIndex where queue.indices.contains(index) {
            recordToHistory(queue[index], playbackHistory: &playbackHistory)
        }
    }

    func previousNavigationTarget(
        currentTime: TimeInterval,
        currentQueueIndex: Int,
        playbackHistoryCount: Int,
        restartThreshold: TimeInterval
    ) -> PlaybackPreviousNavigationTarget {
        if currentTime > restartThreshold {
            return .seekToZero
        }
        if currentQueueIndex > 0 {
            return .queueIndex(currentQueueIndex - 1)
        }
        if playbackHistoryCount > 0 {
            return .historyIndex(playbackHistoryCount - 1)
        }
        return .seekToZero
    }

    func nextPlayableIndex(
        in queue: [QueueItem],
        after startIndex: Int,
        isPlayable: (Track) -> Bool
    ) -> Int? {
        let searchStart = startIndex + 1
        guard searchStart < queue.count else { return nil }

        return queue.indices.first {
            $0 >= searchStart && isPlayable(queue[$0].track)
        }
    }

    func restorePreviousHistoryItem(
        at historyIndex: Int,
        queue: inout [QueueItem],
        playbackHistory: inout [QueueItem],
        currentQueueIndex: Int
    ) -> Int? {
        guard playbackHistory.indices.contains(historyIndex) else { return nil }

        let historyItem = playbackHistory[historyIndex]
        let trackIdentity = historyItem.track.playbackIdentity
        if let existingIndex = queue.firstIndex(where: { $0.track.playbackIdentity == trackIdentity }) {
            playbackHistory.removeSubrange(historyIndex...)
            return existingIndex
        }

        playbackHistory.remove(at: historyIndex)
        let insertPosition = max(0, currentQueueIndex)
        queue.insert(historyItem, at: insertPosition)
        return insertPosition
    }

    func flattenAutoplayItemsBeforeIndex(
        _ index: Int,
        currentQueueIndex: Int,
        queue: inout [QueueItem]
    ) {
        EnsembleQueuePolicy.promoteAutoplayItemsBeforeInsertion(
            index,
            currentQueueIndex: currentQueueIndex,
            queue: &queue,
            source: { $0.source }
        ) { item in
            item.source = .continuePlaying
        }
    }

    func playNextInsertionIndex(in queue: [QueueItem], currentQueueIndex: Int) -> Int {
        EnsembleQueuePolicy.playNextInsertionIndex(
            in: queue,
            currentQueueIndex: currentQueueIndex,
            source: { $0.source }
        )
    }

    func enableShuffle(
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: inout Int,
        playbackHistory: [QueueItem],
        shuffleCandidates: (inout [QueueItem]) -> Void = { $0.shuffle() }
    ) {
        originalQueue = queue
        let currentItem = queue.indices.contains(currentQueueIndex)
            ? queue[currentQueueIndex]
            : nil
        let historyIds = Set(playbackHistory.map(\.track.playbackIdentity))
        var candidates = queue.filter {
            $0.id != currentItem?.id
                && $0.source != .autoplay
                && !historyIds.contains($0.track.playbackIdentity)
        }
        shuffleCandidates(&candidates)

        let autoplayItems = queue.filter { $0.source == .autoplay }
        queue = currentItem.map { [$0] } ?? []
        queue.append(contentsOf: candidates)
        queue.append(contentsOf: autoplayItems)
        currentQueueIndex = currentItem == nil ? -1 : 0
    }

    func disableShuffle(
        queue: inout [QueueItem],
        originalQueue: [QueueItem],
        currentQueueIndex: inout Int
    ) {
        let currentItem = queue.indices.contains(currentQueueIndex)
            ? queue[currentQueueIndex]
            : nil
        queue = originalQueue

        if let currentItem,
           let restoredIndex = queue.firstIndex(where: { $0.id == currentItem.id }) {
            currentQueueIndex = restoredIndex
        }
    }

    func insertUpNext(
        _ items: [QueueItem],
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: Int,
        shuffleEnabled: Bool
    ) {
        let insertIndex = playNextInsertionIndex(
            in: queue,
            currentQueueIndex: currentQueueIndex
        )
        queue.insert(contentsOf: items, at: insertIndex)
        flattenAutoplayItemsBeforeIndex(
            insertIndex,
            currentQueueIndex: currentQueueIndex,
            queue: &queue
        )

        guard shuffleEnabled else { return }

        if queue.indices.contains(currentQueueIndex),
           let originalIndex = originalQueue.firstIndex(where: { $0.id == queue[currentQueueIndex].id }) {
            let originalInsertIndex = playNextInsertionIndex(
                in: originalQueue,
                currentQueueIndex: originalIndex
            )
            originalQueue.insert(contentsOf: items, at: originalInsertIndex)
        } else {
            originalQueue.append(contentsOf: items)
        }
    }

    func insertAtEndOfManualQueue(
        _ items: [QueueItem],
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: Int,
        shuffleEnabled: Bool
    ) {
        let insertIndex = EnsembleQueuePolicy.firstFutureAutoplayIndex(
            in: queue,
            currentQueueIndex: currentQueueIndex,
            source: { $0.source }
        )
        queue.insert(contentsOf: items, at: insertIndex)
        flattenAutoplayItemsBeforeIndex(
            insertIndex,
            currentQueueIndex: currentQueueIndex,
            queue: &queue
        )

        guard shuffleEnabled else { return }

        let originalInsertIndex = originalQueue.firstIndex { $0.source == .autoplay }
            ?? originalQueue.count
        originalQueue.insert(contentsOf: items, at: originalInsertIndex)
    }

    @discardableResult
    func removeItem(
        at index: Int,
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: inout Int,
        shuffleEnabled: Bool
    ) -> QueueItem? {
        guard queue.indices.contains(index), index != currentQueueIndex else { return nil }

        let item = queue.remove(at: index)
        if shuffleEnabled {
            originalQueue.removeAll { $0.id == item.id }
        }
        if index < currentQueueIndex {
            currentQueueIndex -= 1
        }
        return item
    }

    func clear(
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        playbackHistory: inout [QueueItem],
        currentQueueIndex: inout Int
    ) {
        if queue.indices.contains(currentQueueIndex) {
            queue = [queue[currentQueueIndex]]
            currentQueueIndex = 0
        } else {
            queue = []
            currentQueueIndex = -1
        }

        originalQueue = queue
        playbackHistory.removeAll()
    }

    @discardableResult
    func moveItem(
        byId sourceId: String,
        from sourceIndex: Int,
        to destinationIndex: Int,
        destinationSource: QueueItemSource? = nil,
        queue: inout [QueueItem],
        currentQueueIndex: inout Int
    ) -> PlaybackQueueMoveResult? {
        guard queue.indices.contains(sourceIndex),
              destinationIndex >= 0,
              destinationIndex <= queue.count,
              sourceIndex != destinationIndex
                || destinationSource.map({ $0 != queue[sourceIndex].source }) == true,
              queue[sourceIndex].id == sourceId else {
            return nil
        }

        var item = queue.remove(at: sourceIndex)
        if let destinationSource {
            item.source = destinationSource
        } else if item.source == .autoplay {
            item.source = .continuePlaying
        }

        let adjustedDestination = destinationIndex > sourceIndex
            ? destinationIndex - 1
            : destinationIndex
        queue.insert(item, at: adjustedDestination)

        if sourceIndex == currentQueueIndex {
            currentQueueIndex = adjustedDestination
        } else if adjustedDestination <= currentQueueIndex, sourceIndex > currentQueueIndex {
            currentQueueIndex -= 1
        } else if adjustedDestination > currentQueueIndex, sourceIndex < currentQueueIndex {
            currentQueueIndex += 1
        }

        flattenAutoplayItemsBeforeIndex(
            adjustedDestination,
            currentQueueIndex: currentQueueIndex,
            queue: &queue
        )
        return PlaybackQueueMoveResult(item: item, destinationIndex: adjustedDestination)
    }

    private func firstFutureAutoplayIndex(
        in queue: [QueueItem],
        currentQueueIndex: Int
    ) -> Int {
        let firstUpcomingIndex = min(max(currentQueueIndex + 1, 0), queue.count)
        return queue.indices.first {
            $0 >= firstUpcomingIndex && queue[$0].source == .autoplay
        } ?? queue.count
    }

    static func pruneDuplicateFutureAutoplayItems(
        queue: [QueueItem],
        currentQueueIndex: Int
    ) -> PlaybackFutureAutoplayPruneResult {
        guard !queue.isEmpty else {
            return PlaybackFutureAutoplayPruneResult(
                queue: [],
                removedTrackIds: [],
                removedItemCount: 0
            )
        }

        let clampedCurrentIndex = min(max(currentQueueIndex, -1), queue.count - 1)
        let futureStartIndex = max(0, clampedCurrentIndex + 1)
        var seenTrackIdentities = Set<String>()
        var seenVisibleIdentities = Set<AutoplayVisibleTrackIdentity>()
        var prunedQueue = [QueueItem]()
        var removedTrackIds = Set<String>()
        var removedItemCount = 0

        func remember(_ item: QueueItem) {
            seenTrackIdentities.insert(item.track.playbackIdentity)
            if let identity = autoplayVisibleTrackIdentity(for: item.track) {
                seenVisibleIdentities.insert(identity)
            }
        }

        if futureStartIndex > 0 {
            for item in queue[..<futureStartIndex] {
                prunedQueue.append(item)
                remember(item)
            }
        }

        if futureStartIndex < queue.count {
            for item in queue[futureStartIndex...] {
                let isDuplicateAutoplay = item.source == .autoplay && (
                    seenTrackIdentities.contains(item.track.playbackIdentity)
                        || autoplayVisibleTrackIdentity(for: item.track).map(seenVisibleIdentities.contains) == true
                )

                if isDuplicateAutoplay {
                    removedTrackIds.insert(item.track.playbackIdentity)
                    removedItemCount += 1
                } else {
                    prunedQueue.append(item)
                    remember(item)
                }
            }
        }

        return PlaybackFutureAutoplayPruneResult(
            queue: prunedQueue,
            removedTrackIds: removedTrackIds,
            removedItemCount: removedItemCount
        )
    }

    func excessFutureAutoplayIndices(
        queue: [QueueItem],
        currentQueueIndex: Int,
        maximumCount: Int
    ) -> [Int] {
        guard !queue.isEmpty else { return [] }

        let clampedCurrentIndex = min(max(currentQueueIndex, -1), queue.count - 1)
        let futureStartIndex = max(0, clampedCurrentIndex + 1)
        let autoplayIndices = queue.indices.dropFirst(futureStartIndex).filter {
            queue[$0].source == .autoplay
        }
        return Array(autoplayIndices.dropFirst(max(0, maximumCount)))
    }

    static func pruneFutureAutoplayItems(
        queue: [QueueItem],
        currentQueueIndex: Int
    ) -> PlaybackFutureAutoplayPruneResult {
        guard !queue.isEmpty else {
            return PlaybackFutureAutoplayPruneResult(
                queue: [],
                removedTrackIds: [],
                removedItemCount: 0
            )
        }

        let futureStartIndex = max(0, min(currentQueueIndex + 1, queue.count))
        var retained = Array(queue.prefix(futureStartIndex))
        var removedTrackIds = Set<String>()
        var removedItemCount = 0

        for item in queue.dropFirst(futureStartIndex) {
            if item.source == .autoplay {
                removedTrackIds.insert(item.track.playbackIdentity)
                removedItemCount += 1
            } else {
                retained.append(item)
            }
        }

        return PlaybackFutureAutoplayPruneResult(
            queue: retained,
            removedTrackIds: removedTrackIds,
            removedItemCount: removedItemCount
        )
    }

    /// Generated future items are rebuilt from the current seed on restore; manually
    /// queued future items remain part of the persisted queue.
    static func queueForPersistence(
        _ queue: [QueueItem],
        currentItemID: String?
    ) -> [QueueItem] {
        guard let currentItemID,
              let currentIndex = queue.firstIndex(where: { $0.id == currentItemID }) else {
            return queue.filter { $0.source != .autoplay }
        }

        return queue.enumerated().compactMap { index, item in
            index <= currentIndex || item.source != .autoplay ? item : nil
        }
    }

    private struct AutoplayVisibleTrackIdentity: Hashable {
        let normalizedTitle: String
        let normalizedArtist: String
        let durationBucket: Int
    }

    private static func autoplayVisibleTrackIdentity(for track: Track) -> AutoplayVisibleTrackIdentity? {
        let normalizedTitle = normalizedAutoplayDuplicateComponent(track.title)
        let normalizedArtist = normalizedAutoplayDuplicateComponent(track.artistName ?? track.albumArtistName)
        guard !normalizedTitle.isEmpty, !normalizedArtist.isEmpty else { return nil }

        return AutoplayVisibleTrackIdentity(
            normalizedTitle: normalizedTitle,
            normalizedArtist: normalizedArtist,
            durationBucket: Int((max(track.duration, 0) / 2).rounded())
        )
    }

    private static func normalizedAutoplayDuplicateComponent(_ value: String?) -> String {
        let folded = (value ?? "")
            .folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
        return folded
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
    }

    func clearAutoGeneratedTrackIds() {
        legacyAutoGeneratedTrackIds.removeAll()
    }

    func replaceAutoGeneratedTrackIds(with trackIds: Set<String>) {
        legacyAutoGeneratedTrackIds = trackIds
    }

    func syncAutoGeneratedTrackIds(from queue: [QueueItem]) {
        legacyAutoGeneratedTrackIds = Set(queue.filter { $0.source == .autoplay }.map(\.track.playbackIdentity))
    }

    func markAutoGeneratedTrack(id: String) {
        legacyAutoGeneratedTrackIds.insert(id)
    }

    @discardableResult
    func removeAutoGeneratedTrack(id: String) -> Bool {
        legacyAutoGeneratedTrackIds.remove(id) != nil
    }

    func isTrackAutoGenerated(id trackId: String, queue: [QueueItem]) -> Bool {
        queue.contains { $0.track.playbackIdentity == trackId && $0.source == .autoplay }
            || legacyAutoGeneratedTrackIds.contains(trackId)
    }

    @discardableResult
    func updateStreamingQuality(
        _ quality: String,
        queue: inout [QueueItem],
        existingLocalFilePaths: Set<String>? = nil,
        fileExists: (String) -> Bool = { FileManager.default.fileExists(atPath: $0) }
    ) -> Bool {
        var changed = false
        for i in queue.indices {
            if let path = queue[i].track.localFilePath,
               existingLocalFilePaths?.contains(path) ?? fileExists(path) {
                continue
            }
            if queue[i].streamingQuality != quality {
                queue[i].streamingQuality = quality
                changed = true
            }
        }
        return changed
    }

    func refreshDownloadState(
        queue: inout [QueueItem],
        currentQueueIndex: Int,
        fallbackStreamingQuality: String,
        localFilePathForTrack: (Track) async -> String?
    ) async -> PlaybackQueueDownloadRefreshResult {
        var changedTrackIds = Set<String>()
        var nonCurrentTrackIdsNeedingCacheEviction = Set<String>()

        for i in queue.indices {
            let track = queue[i].track
            let currentPath = await localFilePathForTrack(track)
            guard track.localFilePath != currentPath else { continue }

            queue[i] = QueueItem(
                id: queue[i].id,
                track: track.withLocalFilePath(currentPath),
                source: queue[i].source,
                streamingQuality: currentPath == nil ? fallbackStreamingQuality : nil
            )
            changedTrackIds.insert(track.playbackIdentity)

            if i != currentQueueIndex {
                nonCurrentTrackIdsNeedingCacheEviction.insert(track.playbackIdentity)
            }
        }

        return PlaybackQueueDownloadRefreshResult(
            changedTrackIds: changedTrackIds,
            nonCurrentTrackIdsNeedingCacheEviction: nonCurrentTrackIdsNeedingCacheEviction
        )
    }

    func saveSnapshot(
        queue: [QueueItem],
        history: [QueueItem],
        currentIndex: Int,
        currentTime: TimeInterval,
        originalQueue: [QueueItem]? = nil,
        shuffleEnabled: Bool? = nil,
        hasUserQueueEdits: Bool = false
    ) {
        queueStore.save(
            queue: queue,
            history: history,
            currentIndex: currentIndex,
            currentTime: currentTime,
            originalQueue: originalQueue,
            shuffleEnabled: shuffleEnabled,
            hasUserQueueEdits: hasUserQueueEdits
        )
    }

    func saveProgress(_ currentTime: TimeInterval) {
        queueStore.saveProgress(currentTime)
    }

    func loadSnapshot() -> PlaybackQueueSnapshot? {
        queueStore.load()
    }
}
