import Foundation

struct PlaybackQueueDownloadRefreshResult: Equatable {
    let changedTrackIds: Set<String>
    let nonCurrentTrackIdsNeedingCacheEviction: Set<String>

    var changed: Bool {
        !changedTrackIds.isEmpty
    }
}

struct PlaybackQueueMoveResult: Equatable {
    let item: QueueItem
    let destinationIndex: Int
}

/// Owns queue snapshot persistence plus lightweight queue/history mutations that
/// do not need access to playback launch or engine state.
final class PlaybackQueueController {
    private let queueStore: PlaybackQueueStore
    private let maxHistorySize: Int
    private var legacyAutoGeneratedTrackIds: Set<String> = []

    init(queueStore: PlaybackQueueStore, maxHistorySize: Int) {
        self.queueStore = queueStore
        self.maxHistorySize = maxHistorySize
    }

    func recordToHistory(_ item: QueueItem, playbackHistory: inout [QueueItem]) {
        var historyItem = item
        if historyItem.source == .autoplay || historyItem.source == .upNext {
            historyItem.source = .continuePlaying
        }

        guard playbackHistory.last?.track.playbackIdentity != item.track.playbackIdentity else { return }
        playbackHistory.append(historyItem)
        if playbackHistory.count > maxHistorySize {
            playbackHistory.removeFirst()
        }
    }

    func flattenAutoplayItemsBeforeIndex(
        _ index: Int,
        currentQueueIndex: Int,
        queue: inout [QueueItem]
    ) {
        let start = currentQueueIndex + 1
        guard start < queue.count else { return }

        for i in start ..< min(index, queue.count) where queue[i].source == .autoplay {
            queue[i].source = .continuePlaying
        }
    }

    func playNextInsertionIndex(in queue: [QueueItem], currentQueueIndex: Int) -> Int {
        let firstUpcomingIndex = min(max(currentQueueIndex + 1, 0), queue.count)
        let lastUpNextIndex = queue.indices.last {
            $0 >= firstUpcomingIndex && queue[$0].source == .upNext
        }
        return lastUpNextIndex.map { $0 + 1 } ?? firstUpcomingIndex
    }

    func insertUpNext(
        _ items: [QueueItem],
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: Int,
        shuffleEnabled: Bool
    ) {
        let insertIndex = playNextInsertionIndex(
            in: queue,
            currentQueueIndex: currentQueueIndex
        )
        queue.insert(contentsOf: items, at: insertIndex)
        flattenAutoplayItemsBeforeIndex(
            insertIndex,
            currentQueueIndex: currentQueueIndex,
            queue: &queue
        )

        guard shuffleEnabled else { return }

        if queue.indices.contains(currentQueueIndex),
           let originalIndex = originalQueue.firstIndex(where: { $0.id == queue[currentQueueIndex].id }) {
            let originalInsertIndex = playNextInsertionIndex(
                in: originalQueue,
                currentQueueIndex: originalIndex
            )
            originalQueue.insert(contentsOf: items, at: originalInsertIndex)
        } else {
            originalQueue.append(contentsOf: items)
        }
    }

    func insertAtEndOfManualQueue(
        _ items: [QueueItem],
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: Int,
        shuffleEnabled: Bool
    ) {
        let insertIndex = firstFutureAutoplayIndex(
            in: queue,
            currentQueueIndex: currentQueueIndex
        )
        queue.insert(contentsOf: items, at: insertIndex)
        flattenAutoplayItemsBeforeIndex(
            insertIndex,
            currentQueueIndex: currentQueueIndex,
            queue: &queue
        )

        guard shuffleEnabled else { return }

        let originalInsertIndex = originalQueue.firstIndex { $0.source == .autoplay }
            ?? originalQueue.count
        originalQueue.insert(contentsOf: items, at: originalInsertIndex)
    }

    @discardableResult
    func removeItem(
        at index: Int,
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        currentQueueIndex: inout Int,
        shuffleEnabled: Bool
    ) -> QueueItem? {
        guard queue.indices.contains(index), index != currentQueueIndex else { return nil }

        let item = queue.remove(at: index)
        if shuffleEnabled {
            originalQueue.removeAll { $0.id == item.id }
        }
        if index < currentQueueIndex {
            currentQueueIndex -= 1
        }
        return item
    }

    func clear(
        queue: inout [QueueItem],
        originalQueue: inout [QueueItem],
        playbackHistory: inout [QueueItem],
        currentQueueIndex: inout Int
    ) {
        if queue.indices.contains(currentQueueIndex) {
            queue = [queue[currentQueueIndex]]
            currentQueueIndex = 0
        } else {
            queue = []
            currentQueueIndex = -1
        }

        originalQueue = queue
        playbackHistory.removeAll()
    }

    @discardableResult
    func moveItem(
        byId sourceId: String,
        from sourceIndex: Int,
        to destinationIndex: Int,
        queue: inout [QueueItem],
        currentQueueIndex: inout Int
    ) -> PlaybackQueueMoveResult? {
        guard queue.indices.contains(sourceIndex),
              destinationIndex >= 0,
              destinationIndex <= queue.count,
              sourceIndex != destinationIndex,
              queue[sourceIndex].id == sourceId else {
            return nil
        }

        var item = queue.remove(at: sourceIndex)
        if item.source == .autoplay {
            item.source = .continuePlaying
        }

        let adjustedDestination = destinationIndex > sourceIndex
            ? destinationIndex - 1
            : destinationIndex
        queue.insert(item, at: adjustedDestination)

        if sourceIndex == currentQueueIndex {
            currentQueueIndex = adjustedDestination
        } else if adjustedDestination <= currentQueueIndex, sourceIndex > currentQueueIndex {
            currentQueueIndex -= 1
        } else if adjustedDestination > currentQueueIndex, sourceIndex < currentQueueIndex {
            currentQueueIndex += 1
        }

        flattenAutoplayItemsBeforeIndex(
            adjustedDestination,
            currentQueueIndex: currentQueueIndex,
            queue: &queue
        )
        return PlaybackQueueMoveResult(item: item, destinationIndex: adjustedDestination)
    }

    private func firstFutureAutoplayIndex(
        in queue: [QueueItem],
        currentQueueIndex: Int
    ) -> Int {
        let firstUpcomingIndex = min(max(currentQueueIndex + 1, 0), queue.count)
        return queue.indices.first {
            $0 >= firstUpcomingIndex && queue[$0].source == .autoplay
        } ?? queue.count
    }

    func clearAutoGeneratedTrackIds() {
        legacyAutoGeneratedTrackIds.removeAll()
    }

    func replaceAutoGeneratedTrackIds(with trackIds: Set<String>) {
        legacyAutoGeneratedTrackIds = trackIds
    }

    func syncAutoGeneratedTrackIds(from queue: [QueueItem]) {
        legacyAutoGeneratedTrackIds = Set(queue.filter { $0.source == .autoplay }.map(\.track.playbackIdentity))
    }

    func markAutoGeneratedTrack(id: String) {
        legacyAutoGeneratedTrackIds.insert(id)
    }

    @discardableResult
    func removeAutoGeneratedTrack(id: String) -> Bool {
        legacyAutoGeneratedTrackIds.remove(id) != nil
    }

    func isTrackAutoGenerated(id trackId: String, queue: [QueueItem]) -> Bool {
        queue.contains { $0.track.playbackIdentity == trackId && $0.source == .autoplay }
            || legacyAutoGeneratedTrackIds.contains(trackId)
    }

    @discardableResult
    func updateStreamingQuality(
        _ quality: String,
        queue: inout [QueueItem],
        existingLocalFilePaths: Set<String>? = nil,
        fileExists: (String) -> Bool = { FileManager.default.fileExists(atPath: $0) }
    ) -> Bool {
        var changed = false
        for i in queue.indices {
            if let path = queue[i].track.localFilePath,
               existingLocalFilePaths?.contains(path) ?? fileExists(path) {
                continue
            }
            if queue[i].streamingQuality != quality {
                queue[i].streamingQuality = quality
                changed = true
            }
        }
        return changed
    }

    func refreshDownloadState(
        queue: inout [QueueItem],
        currentQueueIndex: Int,
        fallbackStreamingQuality: String,
        localFilePathForTrack: (Track) async -> String?
    ) async -> PlaybackQueueDownloadRefreshResult {
        var changedTrackIds = Set<String>()
        var nonCurrentTrackIdsNeedingCacheEviction = Set<String>()

        for i in queue.indices {
            let track = queue[i].track
            let currentPath = await localFilePathForTrack(track)
            guard track.localFilePath != currentPath else { continue }

            queue[i] = QueueItem(
                id: queue[i].id,
                track: track.withLocalFilePath(currentPath),
                source: queue[i].source,
                streamingQuality: currentPath == nil ? fallbackStreamingQuality : nil
            )
            changedTrackIds.insert(track.playbackIdentity)

            if i != currentQueueIndex {
                nonCurrentTrackIdsNeedingCacheEviction.insert(track.playbackIdentity)
            }
        }

        return PlaybackQueueDownloadRefreshResult(
            changedTrackIds: changedTrackIds,
            nonCurrentTrackIdsNeedingCacheEviction: nonCurrentTrackIdsNeedingCacheEviction
        )
    }

    func saveSnapshot(
        queue: [QueueItem],
        history: [QueueItem],
        currentIndex: Int,
        currentTime: TimeInterval
    ) {
        queueStore.save(
            queue: queue,
            history: history,
            currentIndex: currentIndex,
            currentTime: currentTime
        )
    }

    func loadSnapshot() -> PlaybackQueueSnapshot? {
        queueStore.load()
    }
}
