import Foundation

// MARK: - Queue Navigation Result

/// Describes what PlaybackService should do after a queue navigation action
public enum QueueNavigationAction {
    case playIndex(Int)                 // Play the track at this queue index
    case stop                           // Stop playback (queue exhausted)
    case seekToZero                     // Restart current track
    case refreshAutoplay                // Queue ended but autoplay is enabled
    case repeatAllFromStart             // Queue ended, repeat-all wraps to index 0
}

// MARK: - Queue Manager

/// Manages playback queue state and manipulation logic without any AVFoundation or networking dependencies.
/// This is the single source of truth for queue order, sections, history, shuffle, and autoplay state.
/// PlaybackService delegates all queue operations to this class.
public final class QueueManager {

    // MARK: - Published State

    /// The full playback queue (all sections interleaved)
    public private(set) var queue: [QueueItem] = []

    /// Index of the currently playing track within `queue`
    public private(set) var currentQueueIndex: Int = -1

    /// Chronological log of played tracks (capped at `maxHistorySize`)
    public private(set) var playbackHistory: [QueueItem] = []

    /// Whether shuffle mode is active
    public private(set) var isShuffleEnabled: Bool = false

    /// Current repeat mode
    public private(set) var repeatMode: RepeatMode = .off

    /// Whether autoplay (continuous radio) is enabled
    public private(set) var isAutoplayEnabled: Bool = false

    /// IDs of tracks that were auto-generated (for duplicate filtering)
    public private(set) var autoGeneratedTrackIds: Set<String> = []

    // MARK: - Internal State

    /// Preserved original order for shuffle-off restore
    public private(set) var originalQueue: [QueueItem] = []

    /// Flag to prevent recording to history when navigating backward
    var isNavigatingBackward = false

    // MARK: - Configuration

    public let maxHistorySize: Int
    public let maxQueueLookahead: Int

    // MARK: - Init

    public init(maxHistorySize: Int = 100, maxQueueLookahead: Int = 5) {
        self.maxHistorySize = maxHistorySize
        self.maxQueueLookahead = maxQueueLookahead
    }

    // MARK: - Computed Properties

    /// The currently playing track, if any
    public var currentTrack: Track? {
        guard currentQueueIndex >= 0, currentQueueIndex < queue.count else { return nil }
        return queue[currentQueueIndex].track
    }

    /// Splits the upcoming queue into logical sections for UI display
    public var queueSections: QueueSections {
        guard currentQueueIndex >= 0, currentQueueIndex < queue.count else {
            return .empty
        }
        let upcoming = queue.dropFirst(currentQueueIndex + 1)
        var upNext: [QueueItem] = []
        var continuePlaying: [QueueItem] = []
        var autoplay: [QueueItem] = []

        for item in upcoming {
            switch item.source {
            case .upNext: upNext.append(item)
            case .continuePlaying: continuePlaying.append(item)
            case .autoplay: autoplay.append(item)
            }
        }
        return QueueSections(upNext: upNext, continuePlaying: continuePlaying, autoplay: autoplay)
    }

    /// Index of the first autoplay item after currentQueueIndex, or queue.count if none
    public var autoplayStartIndex: Int {
        for i in (currentQueueIndex + 1)..<queue.count {
            if queue[i].source == .autoplay {
                return i
            }
        }
        return queue.count
    }

    /// Index of the last non-autoplay item in the queue (for autoplay seed selection)
    public var lastRealTrackIndex: Int? {
        for i in stride(from: queue.count - 1, through: 0, by: -1) {
            if queue[i].source != .autoplay {
                return i
            }
        }
        return nil
    }

    // MARK: - Queue Setup

    /// Set up a new queue from a list of tracks, starting at the given index.
    /// Clears history and autoplay state.
    /// Returns the index to start playing.
    @discardableResult
    public func setQueue(tracks: [Track], startingAt index: Int) -> Int? {
        guard !tracks.isEmpty, index >= 0, index < tracks.count else { return nil }

        // Disable shuffle on regular play
        if isShuffleEnabled {
            isShuffleEnabled = false
        }

        queue = tracks.map { QueueItem(track: $0, source: .continuePlaying) }
        originalQueue = queue
        currentQueueIndex = index

        // Clear history and autoplay state for fresh session
        playbackHistory.removeAll()
        autoGeneratedTrackIds.removeAll()

        return index
    }

    /// Set up a shuffled queue from a list of tracks. Enables shuffle mode.
    /// Returns the index to start playing (always 0).
    @discardableResult
    public func setShuffledQueue(tracks: [Track]) -> Int? {
        guard !tracks.isEmpty else { return nil }

        isShuffleEnabled = true

        let items = tracks.map { QueueItem(track: $0, source: .continuePlaying) }
        originalQueue = items

        var shuffled = items
        shuffled.shuffle()

        queue = shuffled
        currentQueueIndex = 0

        playbackHistory.removeAll()
        autoGeneratedTrackIds.removeAll()

        return 0
    }

    // MARK: - Queue Navigation

    /// Advance to the next track. Returns the action PlaybackService should take.
    public func next() -> QueueNavigationAction {
        guard !queue.isEmpty else { return .stop }

        // Record current track to history before advancing
        if currentQueueIndex >= 0, currentQueueIndex < queue.count {
            recordToHistory(queue[currentQueueIndex])
        }

        let nextIndex = currentQueueIndex + 1
        if nextIndex >= queue.count {
            // Queue ended
            if repeatMode == .all {
                currentQueueIndex = 0
                return .repeatAllFromStart
            } else if isAutoplayEnabled {
                return .refreshAutoplay
            } else {
                return .stop
            }
        } else {
            currentQueueIndex = nextIndex
            return .playIndex(nextIndex)
        }
    }

    /// Go to the previous track. Returns the action PlaybackService should take.
    public func previous(currentTime: TimeInterval) -> QueueNavigationAction {
        // If more than 3 seconds in, restart current track
        if currentTime > 3 {
            return .seekToZero
        }

        // Can't go further back
        guard currentQueueIndex > 0 else {
            return .seekToZero
        }

        // Set flag to prevent recording to history when navigating backward
        isNavigatingBackward = true

        // Remove the last item from history to prevent duplicates when going forward again
        if !playbackHistory.isEmpty {
            playbackHistory.removeLast()
        }

        currentQueueIndex -= 1
        return .playIndex(currentQueueIndex)
    }

    /// Jump to a specific queue index. Records skipped tracks to history.
    /// Returns the action PlaybackService should take.
    public func jumpToIndex(_ index: Int) -> QueueNavigationAction? {
        guard index >= 0, index < queue.count else { return nil }

        // Record current track to history before jumping
        if currentQueueIndex >= 0, currentQueueIndex < queue.count {
            recordToHistory(queue[currentQueueIndex])
        }

        // When jumping forward, record all skipped tracks to history
        if index > currentQueueIndex {
            for i in (currentQueueIndex + 1)..<index {
                if i >= 0, i < queue.count {
                    recordToHistory(queue[i])
                }
            }
        }

        currentQueueIndex = index
        return .playIndex(index)
    }

    /// Play a track from history. Returns the action PlaybackService should take.
    public func playFromHistory(at historyIndex: Int) -> QueueNavigationAction? {
        guard historyIndex >= 0, historyIndex < playbackHistory.count else { return nil }

        let historyItem = playbackHistory[historyIndex]
        let trackId = historyItem.track.id

        // Check if this track already exists in the queue
        if let existingIndex = queue.firstIndex(where: { $0.track.id == trackId }) {
            // Track exists in queue - navigate to it
            playbackHistory.removeSubrange(historyIndex...)
            isNavigatingBackward = true
            currentQueueIndex = existingIndex
            return .playIndex(existingIndex)
        } else {
            // Track not in queue - insert it at current position
            playbackHistory.remove(at: historyIndex)
            let insertPosition = max(0, currentQueueIndex)
            queue.insert(historyItem, at: insertPosition)
            currentQueueIndex = insertPosition
            isNavigatingBackward = true
            return .playIndex(insertPosition)
        }
    }

    // MARK: - Queue Manipulation

    /// Insert a track to play immediately after the current track (Up Next section)
    public func playNext(_ track: Track) {
        let item = QueueItem(track: track, source: .upNext)
        let insertIndex = currentQueueIndex + 1
        if insertIndex <= queue.count {
            queue.insert(item, at: insertIndex)
            // If inserted among autoplay items, flatten preceding autoplay
            flattenAutoplayItemsBeforeIndex(insertIndex)
        } else {
            queue.append(item)
        }

        // Keep originalQueue in sync for shuffle restore
        if isShuffleEnabled {
            if let currentItem = (currentQueueIndex >= 0 && currentQueueIndex < queue.count) ? queue[currentQueueIndex] : nil,
               let originalIdx = originalQueue.firstIndex(where: { $0.id == currentItem.id }) {
                originalQueue.insert(item, at: originalIdx + 1)
            } else {
                originalQueue.append(item)
            }
        }
    }

    /// Insert multiple tracks to play immediately after the current track, preserving order
    public func playNext(_ tracks: [Track]) {
        guard !tracks.isEmpty else { return }
        let items = tracks.map { QueueItem(track: $0, source: .upNext) }
        let insertIndex = currentQueueIndex + 1
        if insertIndex <= queue.count {
            queue.insert(contentsOf: items, at: insertIndex)
            // If inserted among autoplay items, flatten preceding autoplay
            flattenAutoplayItemsBeforeIndex(insertIndex)
        } else {
            queue.append(contentsOf: items)
        }

        // Keep originalQueue in sync for shuffle restore
        if isShuffleEnabled {
            if let currentItem = (currentQueueIndex >= 0 && currentQueueIndex < queue.count) ? queue[currentQueueIndex] : nil,
               let originalIdx = originalQueue.firstIndex(where: { $0.id == currentItem.id }) {
                originalQueue.insert(contentsOf: items, at: originalIdx + 1)
            } else {
                originalQueue.append(contentsOf: items)
            }
        }
    }

    /// Add a track to end of the "real" queue (before autoplay tracks)
    public func playLast(_ track: Track) {
        let item = QueueItem(track: track, source: .continuePlaying)
        let insertIndex = autoplayStartIndex
        queue.insert(item, at: insertIndex)
        flattenAutoplayItemsBeforeIndex(insertIndex)

        if isShuffleEnabled {
            let originalAutoplayStart = originalQueue.firstIndex(where: { $0.source == .autoplay }) ?? originalQueue.count
            originalQueue.insert(item, at: originalAutoplayStart)
        }
    }

    /// Add multiple tracks to end of the "real" queue (before autoplay tracks)
    public func playLast(_ tracks: [Track]) {
        let items = tracks.map { QueueItem(track: $0, source: .continuePlaying) }
        let insertIndex = autoplayStartIndex
        queue.insert(contentsOf: items, at: insertIndex)
        flattenAutoplayItemsBeforeIndex(insertIndex)

        if isShuffleEnabled {
            let originalAutoplayStart = originalQueue.firstIndex(where: { $0.source == .autoplay }) ?? originalQueue.count
            originalQueue.insert(contentsOf: items, at: originalAutoplayStart)
        }
    }

    /// Add a track to end of queue (before autoplay). Alias for playLast.
    public func addToQueue(_ track: Track) {
        playLast(track)
    }

    /// Add tracks to end of queue (before autoplay). Alias for playLast.
    public func addToQueue(_ tracks: [Track]) {
        playLast(tracks)
    }

    /// Remove a track from the queue at the given index. Cannot remove the currently playing track.
    /// Returns true if the item was removed.
    @discardableResult
    public func removeFromQueue(at index: Int) -> Bool {
        guard index >= 0, index < queue.count else { return false }
        guard index != currentQueueIndex else { return false }

        let item = queue.remove(at: index)

        // Keep originalQueue in sync for shuffle restore
        if isShuffleEnabled {
            originalQueue.removeAll { $0.id == item.id }
        }

        // Adjust current index if needed
        if index < currentQueueIndex {
            currentQueueIndex -= 1
        }

        return true
    }

    /// Clear the queue, keeping only the currently playing track.
    public func clearQueue() {
        let currentItem = currentQueueIndex >= 0 && currentQueueIndex < queue.count ? queue[currentQueueIndex] : nil

        if let item = currentItem {
            queue = [item]
            currentQueueIndex = 0
        } else {
            queue = []
            currentQueueIndex = -1
        }

        originalQueue = queue
        playbackHistory.removeAll()
    }

    /// Move a queue item by ID from source position to destination position.
    /// If an autoplay item is moved, it gets flattened to continuePlaying.
    public func moveQueueItem(byId sourceId: String, from sourceIndex: Int, to destinationIndex: Int) {
        guard sourceIndex >= 0, sourceIndex < queue.count,
              destinationIndex >= 0, destinationIndex <= queue.count,
              sourceIndex != destinationIndex else { return }

        // Verify the source index actually contains the item with this ID
        guard queue[sourceIndex].id == sourceId else { return }

        // Remove from source
        var item = queue.remove(at: sourceIndex)

        // If an autoplay item is moved by the user, flatten it to continuePlaying
        if item.source == .autoplay {
            item.source = .continuePlaying
        }

        // Adjust destination if removing shifted it
        let adjustedDest = destinationIndex > sourceIndex ? destinationIndex - 1 : destinationIndex

        // Insert at destination
        queue.insert(item, at: adjustedDest)

        // Update currentQueueIndex if needed
        if sourceIndex == currentQueueIndex {
            currentQueueIndex = adjustedDest
        } else if adjustedDest <= currentQueueIndex && sourceIndex > currentQueueIndex {
            currentQueueIndex -= 1
        } else if adjustedDest > currentQueueIndex && sourceIndex < currentQueueIndex {
            currentQueueIndex += 1
        }

        // Flatten autoplay items that now appear before the moved item
        flattenAutoplayItemsBeforeIndex(adjustedDest)
    }

    /// Move a queue item from one relative position to another (relative to currentQueueIndex).
    /// @deprecated Use moveQueueItem(byId:from:to:) instead.
    public func moveQueueItem(from sourceIndex: Int, to destinationIndex: Int) {
        let queueStartIndex = currentQueueIndex + 1
        let absSource = queueStartIndex + sourceIndex
        let absDest = queueStartIndex + destinationIndex

        guard absSource >= queueStartIndex, absSource < queue.count,
              absDest >= queueStartIndex, absDest <= queue.count else { return }

        var item = queue.remove(at: absSource)

        // If an autoplay item is moved by the user, flatten it to continuePlaying
        if item.source == .autoplay {
            item.source = .continuePlaying
        }

        let adjustedDest = absDest > absSource ? absDest - 1 : absDest
        queue.insert(item, at: adjustedDest)

        // Flatten autoplay items that now appear before the moved item
        flattenAutoplayItemsBeforeIndex(adjustedDest)
    }

    // MARK: - Shuffle

    /// Toggle shuffle mode. When enabling, shuffles future non-autoplay tracks.
    /// When disabling, restores original order.
    public func toggleShuffle() {
        isShuffleEnabled.toggle()

        if isShuffleEnabled {
            // Save original queue for restore
            originalQueue = queue

            let currentItem = (currentQueueIndex >= 0 && currentQueueIndex < queue.count)
                ? queue[currentQueueIndex] : nil

            // Candidates for shuffling: everything except current track and autoplay
            var candidates = queue.filter { item in
                let isCurrent = (item.id == currentItem?.id)
                let isAutoplay = (item.source == .autoplay)
                return !isCurrent && !isAutoplay
            }

            // Filter out candidates that are already in history
            let historyIds = Set(playbackHistory.map { $0.track.id })
            candidates.removeAll { historyIds.contains($0.track.id) }

            candidates.shuffle()

            // Autoplay items are kept at the very end
            let autoplayItems = queue.filter { $0.source == .autoplay }

            // Rebuild: [current] [shuffled candidates] [autoplay]
            var newQueue: [QueueItem] = []
            if let current = currentItem {
                newQueue.append(current)
            }
            newQueue.append(contentsOf: candidates)
            newQueue.append(contentsOf: autoplayItems)

            queue = newQueue
            currentQueueIndex = currentItem != nil ? 0 : -1
        } else {
            // Restore original queue order
            let currentItem = currentQueueIndex >= 0 && currentQueueIndex < queue.count
                ? queue[currentQueueIndex] : nil

            queue = originalQueue

            if let item = currentItem, let index = queue.firstIndex(where: { $0.id == item.id }) {
                currentQueueIndex = index
            }
        }
    }

    /// Cycle repeat mode: off -> all -> one -> off
    public func cycleRepeatMode() {
        let nextRawValue = (repeatMode.rawValue + 1) % RepeatMode.allCases.count
        repeatMode = RepeatMode(rawValue: nextRawValue) ?? .off
    }

    // MARK: - Autoplay

    /// Toggle autoplay. When disabling, removes all autoplay items from queue.
    /// Returns true if autoplay was just enabled (caller should refresh autoplay queue).
    @discardableResult
    public func toggleAutoplay() -> Bool {
        isAutoplayEnabled.toggle()

        if !isAutoplayEnabled {
            // Remove all autoplay items from queue
            queue.removeAll { $0.source == .autoplay }
            autoGeneratedTrackIds.removeAll()
            return false
        }

        return true // Caller should fetch autoplay tracks
    }

    /// Add autoplay tracks to the end of the queue. Filters out duplicates.
    /// Returns the tracks that were actually added.
    @discardableResult
    public func addAutoplayTracks(_ tracks: [Track]) -> [Track] {
        let existingQueueIds = Set(queue.map { $0.track.id })
        let uniqueNewTracks = tracks.filter { !existingQueueIds.contains($0.id) }

        for track in uniqueNewTracks {
            let item = QueueItem(track: track, source: .autoplay)
            queue.append(item)
            autoGeneratedTrackIds.insert(track.id)
        }

        // Trim excess
        trimAutoplayQueue()

        return uniqueNewTracks
    }

    /// Trims auto-generated tracks from queue if future count exceeds maxQueueLookahead
    public func trimAutoplayQueue() {
        let futureTracksCount = max(0, queue.count - currentQueueIndex - 1)

        if futureTracksCount > maxQueueLookahead {
            let tracksToRemove = futureTracksCount - maxQueueLookahead
            let removeStartIndex = queue.count - tracksToRemove

            for i in (removeStartIndex..<queue.count).reversed() {
                let removedTrack = queue[i].track
                if autoGeneratedTrackIds.contains(removedTrack.id) {
                    autoGeneratedTrackIds.remove(removedTrack.id)
                }
                queue.remove(at: i)
            }
        }
    }

    /// Whether the queue needs more autoplay tracks
    public var needsAutoplayRefresh: Bool {
        guard isAutoplayEnabled else { return false }
        let remaining = queue.count - currentQueueIndex - 1
        return remaining < maxQueueLookahead
    }

    /// Check if a track was auto-generated
    public func isTrackAutoGenerated(trackId: String) -> Bool {
        return queue.contains { $0.track.id == trackId && $0.source == .autoplay }
            || autoGeneratedTrackIds.contains(trackId)
    }

    // MARK: - History

    /// Records the given item to history. Flattens autoplay/upNext source to continuePlaying.
    /// Avoids consecutive duplicates.
    public func recordToHistory(_ item: QueueItem) {
        var historyItem = item
        if historyItem.source == .autoplay || historyItem.source == .upNext {
            historyItem.source = .continuePlaying
        }

        // Avoid consecutive duplicates
        if playbackHistory.last?.track.id != item.track.id {
            playbackHistory.append(historyItem)
            if playbackHistory.count > maxHistorySize {
                playbackHistory.removeFirst()
            }
        }
    }

    /// Called by PlaybackService when an item change is detected, to record history
    /// and reset the backward navigation flag.
    /// Returns true if this was not a backward navigation (i.e., history was recorded).
    @discardableResult
    public func handleItemAdvance(from previousIndex: Int) -> Bool {
        let wasNavigatingBackward = isNavigatingBackward
        isNavigatingBackward = false

        if !wasNavigatingBackward, previousIndex >= 0, previousIndex < queue.count {
            recordToHistory(queue[previousIndex])
            return true
        }
        return false
    }

    // MARK: - Flatten Helpers

    /// Flattens autoplay items that appear before the given index to .continuePlaying.
    /// Called when a user inserts or moves a non-autoplay item among autoplay items.
    public func flattenAutoplayItemsBeforeIndex(_ index: Int) {
        let start = currentQueueIndex + 1
        let end = min(index, queue.count)
        guard start < end else { return }
        for i in start..<end {
            if queue[i].source == .autoplay {
                queue[i].source = .continuePlaying
            }
        }
    }

    // MARK: - State Restoration

    /// Restore queue state from saved data
    public func restore(queue: [QueueItem], history: [QueueItem], currentIndex: Int) {
        self.queue = queue
        self.originalQueue = queue
        self.currentQueueIndex = currentIndex
        self.playbackHistory = history
    }

    /// For testing: directly set the internal queue state
    internal func _setQueueState(
        queue: [QueueItem],
        currentIndex: Int,
        originalQueue: [QueueItem]? = nil,
        history: [QueueItem] = [],
        isShuffleEnabled: Bool = false,
        isAutoplayEnabled: Bool = false,
        repeatMode: RepeatMode = .off
    ) {
        self.queue = queue
        self.currentQueueIndex = currentIndex
        self.originalQueue = originalQueue ?? queue
        self.playbackHistory = history
        self.isShuffleEnabled = isShuffleEnabled
        self.isAutoplayEnabled = isAutoplayEnabled
        self.repeatMode = repeatMode
    }
}
