@testable import EnsembleCore
import XCTest

final class PlaybackQueueControllerTests: XCTestCase {
    func testRecordToHistoryNormalizesManualSourcesAndSkipsConsecutiveDuplicates() {
        let controller = makeController()
        let track = makeTrack(id: "played")
        var history = [QueueItem]()

        controller.recordToHistory(
            QueueItem(track: track, source: .upNext),
            playbackHistory: &history
        )
        controller.recordToHistory(
            QueueItem(track: track, source: .autoplay),
            playbackHistory: &history
        )

        XCTAssertEqual(history.count, 1)
        XCTAssertEqual(history[0].track.playbackIdentity, track.playbackIdentity)
        XCTAssertEqual(history[0].source, .continuePlaying)
    }

    func testRecordToHistoryKeepsMostRecentItemsWithinLimit() {
        let controller = makeController(maxHistorySize: 2)
        var history = [
            QueueItem(track: makeTrack(id: "oldest")),
            QueueItem(track: makeTrack(id: "middle")),
        ]

        controller.recordToHistory(
            QueueItem(track: makeTrack(id: "newest")),
            playbackHistory: &history
        )

        XCTAssertEqual(history.map(\.track.id), ["middle", "newest"])
    }

    func testFlattenAutoplayItemsOnlyChangesUpcomingItemsBeforeInsertion() {
        let controller = makeController()
        var queue = [
            QueueItem(track: makeTrack(id: "history-auto"), source: .autoplay),
            QueueItem(track: makeTrack(id: "current")),
            QueueItem(track: makeTrack(id: "upcoming-auto"), source: .autoplay),
            QueueItem(track: makeTrack(id: "boundary-auto"), source: .autoplay),
        ]

        controller.flattenAutoplayItemsBeforeIndex(
            3,
            currentQueueIndex: 1,
            queue: &queue
        )

        XCTAssertEqual(queue.map(\.source), [
            .autoplay,
            .continuePlaying,
            .continuePlaying,
            .autoplay,
        ])
    }

    func testAutoGeneratedIdentityPrefersQueueItemSource() {
        let controller = makeController()
        let manual = makeTrack(id: "manual")
        let autoplay = makeTrack(id: "autoplay")
        let queue = [
            QueueItem(track: manual, source: .continuePlaying),
            QueueItem(track: autoplay, source: .autoplay),
        ]

        XCTAssertTrue(controller.isTrackAutoGenerated(id: autoplay.playbackIdentity, queue: queue))
        XCTAssertFalse(controller.isTrackAutoGenerated(id: manual.playbackIdentity, queue: queue))
    }

    func testPlayNextInsertionStartsImmediatelyAfterCurrentItem() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "current")),
            QueueItem(track: makeTrack(id: "original")),
            QueueItem(track: makeTrack(id: "autoplay"), source: .autoplay),
        ]

        XCTAssertEqual(controller.playNextInsertionIndex(in: queue, currentQueueIndex: 0), 1)
    }

    func testPlayNextInsertionAppendsAfterExistingUpNextItems() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "current")),
            QueueItem(track: makeTrack(id: "added-1"), source: .upNext),
            QueueItem(track: makeTrack(id: "added-2"), source: .upNext),
            QueueItem(track: makeTrack(id: "original")),
            QueueItem(track: makeTrack(id: "autoplay"), source: .autoplay),
        ]

        XCTAssertEqual(controller.playNextInsertionIndex(in: queue, currentQueueIndex: 0), 3)
    }

    func testPlayNextInsertionStaysAtEndOfAddedListInsteadOfEntireQueue() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "current")),
            QueueItem(track: makeTrack(id: "added"), source: .upNext),
            QueueItem(track: makeTrack(id: "original-1")),
            QueueItem(track: makeTrack(id: "original-2")),
            QueueItem(track: makeTrack(id: "autoplay"), source: .autoplay),
        ]

        XCTAssertEqual(controller.playNextInsertionIndex(in: queue, currentQueueIndex: 0), 2)
    }

    func testAutoGeneratedIdentityDistinguishesDuplicateRatingKeys() {
        let controller = makeController()
        let subscriberTrack = makeTrack(id: "7551", sourceCompositeKey: "plex:felicity:server:music")
        let freeAccountTrack = makeTrack(id: "7551", sourceCompositeKey: "plex:felicity-test:server:music")
        let queue = [
            QueueItem(track: subscriberTrack, source: .continuePlaying),
            QueueItem(track: freeAccountTrack, source: .autoplay),
        ]

        XCTAssertFalse(controller.isTrackAutoGenerated(id: subscriberTrack.playbackIdentity, queue: queue))
        XCTAssertTrue(controller.isTrackAutoGenerated(id: freeAccountTrack.playbackIdentity, queue: queue))
    }

    func testAutoGeneratedIdentityFallsBackToLegacyTrackedIds() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "legacy"), source: .continuePlaying),
        ]

        controller.markAutoGeneratedTrack(id: "legacy")

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "legacy", queue: queue))
    }

    func testAutoGeneratedTrackingCanClearReplaceAndSyncFromQueue() {
        let controller = makeController()
        controller.replaceAutoGeneratedTrackIds(with: ["radio-seed", "stale"])

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "radio-seed", queue: []))
        XCTAssertTrue(controller.removeAutoGeneratedTrack(id: "stale"))
        XCTAssertFalse(controller.isTrackAutoGenerated(id: "stale", queue: []))

        let queue = [
            QueueItem(track: makeTrack(id: "manual"), source: .continuePlaying),
            QueueItem(track: makeTrack(id: "restored-auto"), source: .autoplay),
        ]
        controller.syncAutoGeneratedTrackIds(from: queue)

        XCTAssertFalse(controller.isTrackAutoGenerated(id: "radio-seed", queue: []))
        XCTAssertTrue(controller.isTrackAutoGenerated(id: queue[1].track.playbackIdentity, queue: []))

        controller.clearAutoGeneratedTrackIds()

        XCTAssertFalse(controller.isTrackAutoGenerated(id: queue[1].track.playbackIdentity, queue: []))
    }

    func testUpdateStreamingQualitySkipsDownloadedFilesAndRestampsStreamingItems() {
        let controller = makeController()
        var queue = [
            QueueItem(
                track: makeTrack(id: "downloaded", localFilePath: "/downloads/downloaded.mp3"),
                streamingQuality: "old"
            ),
            QueueItem(
                track: makeTrack(id: "missing-local", localFilePath: "/downloads/missing.mp3"),
                streamingQuality: "old"
            ),
            QueueItem(track: makeTrack(id: "streaming"), streamingQuality: "old"),
        ]

        let changed = controller.updateStreamingQuality(
            "medium",
            queue: &queue,
            fileExists: { $0 == "/downloads/downloaded.mp3" }
        )

        XCTAssertTrue(changed)
        XCTAssertEqual(queue[0].streamingQuality, "old")
        XCTAssertEqual(queue[1].streamingQuality, "medium")
        XCTAssertEqual(queue[2].streamingQuality, "medium")

        let unchanged = controller.updateStreamingQuality(
            "medium",
            queue: &queue,
            fileExists: { $0 == "/downloads/downloaded.mp3" }
        )

        XCTAssertFalse(unchanged)
    }

    func testUpdateStreamingQualityUsesPrecomputedExistingLocalPaths() {
        let controller = makeController()
        var queue = [
            QueueItem(
                track: makeTrack(id: "downloaded", localFilePath: "/downloads/downloaded.mp3"),
                streamingQuality: "old"
            ),
            QueueItem(
                track: makeTrack(id: "missing-local", localFilePath: "/downloads/missing.mp3"),
                streamingQuality: "old"
            ),
        ]

        var fileExistsCalls = 0
        let changed = controller.updateStreamingQuality(
            "medium",
            queue: &queue,
            existingLocalFilePaths: ["/downloads/downloaded.mp3"],
            fileExists: { _ in
                fileExistsCalls += 1
                return false
            }
        )

        XCTAssertTrue(changed)
        XCTAssertEqual(fileExistsCalls, 0)
        XCTAssertEqual(queue[0].streamingQuality, "old")
        XCTAssertEqual(queue[1].streamingQuality, "medium")
    }

    func testRefreshDownloadStateAddsLocalPathClearsQualityAndReportsNonCurrentEviction() async {
        let controller = makeController()
        var queue = [
            QueueItem(track: makeTrack(id: "current"), streamingQuality: "high"),
            QueueItem(
                id: "queue-next",
                track: makeTrack(id: "next"),
                source: .upNext,
                streamingQuality: "high"
            ),
        ]

        let result = await controller.refreshDownloadState(
            queue: &queue,
            currentQueueIndex: 0,
            fallbackStreamingQuality: "medium",
            localFilePathForTrack: { track in
                track.id == "next" ? "/downloads/next.mp3" : nil
            }
        )

        XCTAssertEqual(result.changedTrackIds, [queue[1].track.playbackIdentity])
        XCTAssertEqual(result.nonCurrentTrackIdsNeedingCacheEviction, [queue[1].track.playbackIdentity])
        XCTAssertEqual(queue[1].id, "queue-next")
        XCTAssertEqual(queue[1].source, .upNext)
        XCTAssertEqual(queue[1].track.localFilePath, "/downloads/next.mp3")
        XCTAssertNil(queue[1].streamingQuality)
        XCTAssertEqual(queue[1].track.albumArtistName, "Album Artist")
        XCTAssertEqual(queue[1].track.genres, ["Electronic", "Test"])
    }

    func testRefreshDownloadStateRemovesCurrentLocalPathAndRestampsQualityWithoutEviction() async {
        let controller = makeController()
        var queue = [
            QueueItem(
                track: makeTrack(id: "current", localFilePath: "/downloads/current.mp3"),
                streamingQuality: nil
            ),
            QueueItem(
                track: makeTrack(id: "next", localFilePath: "/downloads/next.mp3"),
                streamingQuality: nil
            ),
        ]

        let result = await controller.refreshDownloadState(
            queue: &queue,
            currentQueueIndex: 0,
            fallbackStreamingQuality: "low",
            localFilePathForTrack: { track in
                track.id == "current" ? nil : track.localFilePath
            }
        )

        XCTAssertEqual(result.changedTrackIds, [queue[0].track.playbackIdentity])
        XCTAssertTrue(result.nonCurrentTrackIdsNeedingCacheEviction.isEmpty)
        XCTAssertNil(queue[0].track.localFilePath)
        XCTAssertEqual(queue[0].streamingQuality, "low")
        XCTAssertEqual(queue[1].track.localFilePath, "/downloads/next.mp3")
        XCTAssertNil(queue[1].streamingQuality)
    }

    private func makeController(maxHistorySize: Int = 100) -> PlaybackQueueController {
        PlaybackQueueController(
            queueStore: PlaybackQueueStore(defaults: .standard),
            maxHistorySize: maxHistorySize
        )
    }

    private func makeTrack(
        id: String,
        localFilePath: String? = nil,
        sourceCompositeKey: String? = "plex:account:server:library"
    ) -> Track {
        Track(
            id: id,
            key: "/library/metadata/\(id)",
            title: "Track \(id)",
            artistName: "Artist",
            albumArtistName: "Album Artist",
            localFilePath: localFilePath,
            genres: ["Electronic", "Test"],
            sourceCompositeKey: sourceCompositeKey
        )
    }
}
