@testable import EnsembleCore
import XCTest

final class PlaybackQueueControllerTests: XCTestCase {
    func testAutoGeneratedIdentityPrefersQueueItemSource() {
        let controller = makeController()
        let manual = makeTrack(id: "manual")
        let autoplay = makeTrack(id: "autoplay")
        let queue = [
            QueueItem(track: manual, source: .continuePlaying),
            QueueItem(track: autoplay, source: .autoplay),
        ]

        XCTAssertTrue(controller.isTrackAutoGenerated(id: autoplay.playbackIdentity, queue: queue))
        XCTAssertFalse(controller.isTrackAutoGenerated(id: manual.playbackIdentity, queue: queue))
    }

    func testAutoGeneratedIdentityDistinguishesDuplicateRatingKeys() {
        let controller = makeController()
        let subscriberTrack = makeTrack(id: "7551", sourceCompositeKey: "plex:felicity:server:music")
        let freeAccountTrack = makeTrack(id: "7551", sourceCompositeKey: "plex:felicity-test:server:music")
        let queue = [
            QueueItem(track: subscriberTrack, source: .continuePlaying),
            QueueItem(track: freeAccountTrack, source: .autoplay),
        ]

        XCTAssertFalse(controller.isTrackAutoGenerated(id: subscriberTrack.playbackIdentity, queue: queue))
        XCTAssertTrue(controller.isTrackAutoGenerated(id: freeAccountTrack.playbackIdentity, queue: queue))
    }

    func testAutoGeneratedIdentityFallsBackToLegacyTrackedIds() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "legacy"), source: .continuePlaying),
        ]

        controller.markAutoGeneratedTrack(id: "legacy")

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "legacy", queue: queue))
    }

    func testAutoGeneratedTrackingCanClearReplaceAndSyncFromQueue() {
        let controller = makeController()
        controller.replaceAutoGeneratedTrackIds(with: ["radio-seed", "stale"])

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "radio-seed", queue: []))
        XCTAssertTrue(controller.removeAutoGeneratedTrack(id: "stale"))
        XCTAssertFalse(controller.isTrackAutoGenerated(id: "stale", queue: []))

        let queue = [
            QueueItem(track: makeTrack(id: "manual"), source: .continuePlaying),
            QueueItem(track: makeTrack(id: "restored-auto"), source: .autoplay),
        ]
        controller.syncAutoGeneratedTrackIds(from: queue)

        XCTAssertFalse(controller.isTrackAutoGenerated(id: "radio-seed", queue: []))
        XCTAssertTrue(controller.isTrackAutoGenerated(id: queue[1].track.playbackIdentity, queue: []))

        controller.clearAutoGeneratedTrackIds()

        XCTAssertFalse(controller.isTrackAutoGenerated(id: queue[1].track.playbackIdentity, queue: []))
    }

    func testUpdateStreamingQualitySkipsDownloadedFilesAndRestampsStreamingItems() {
        let controller = makeController()
        var queue = [
            QueueItem(
                track: makeTrack(id: "downloaded", localFilePath: "/downloads/downloaded.mp3"),
                streamingQuality: "old"
            ),
            QueueItem(
                track: makeTrack(id: "missing-local", localFilePath: "/downloads/missing.mp3"),
                streamingQuality: "old"
            ),
            QueueItem(track: makeTrack(id: "streaming"), streamingQuality: "old"),
        ]

        let changed = controller.updateStreamingQuality(
            "medium",
            queue: &queue,
            fileExists: { $0 == "/downloads/downloaded.mp3" }
        )

        XCTAssertTrue(changed)
        XCTAssertEqual(queue[0].streamingQuality, "old")
        XCTAssertEqual(queue[1].streamingQuality, "medium")
        XCTAssertEqual(queue[2].streamingQuality, "medium")

        let unchanged = controller.updateStreamingQuality(
            "medium",
            queue: &queue,
            fileExists: { $0 == "/downloads/downloaded.mp3" }
        )

        XCTAssertFalse(unchanged)
    }

    func testRefreshDownloadStateAddsLocalPathClearsQualityAndReportsNonCurrentEviction() async {
        let controller = makeController()
        var queue = [
            QueueItem(track: makeTrack(id: "current"), streamingQuality: "high"),
            QueueItem(
                id: "queue-next",
                track: makeTrack(id: "next"),
                source: .upNext,
                streamingQuality: "high"
            ),
        ]

        let result = await controller.refreshDownloadState(
            queue: &queue,
            currentQueueIndex: 0,
            fallbackStreamingQuality: "medium",
            localFilePathForTrack: { track in
                track.id == "next" ? "/downloads/next.mp3" : nil
            }
        )

        XCTAssertEqual(result.changedTrackIds, [queue[1].track.playbackIdentity])
        XCTAssertEqual(result.nonCurrentTrackIdsNeedingCacheEviction, [queue[1].track.playbackIdentity])
        XCTAssertEqual(queue[1].id, "queue-next")
        XCTAssertEqual(queue[1].source, .upNext)
        XCTAssertEqual(queue[1].track.localFilePath, "/downloads/next.mp3")
        XCTAssertNil(queue[1].streamingQuality)
        XCTAssertEqual(queue[1].track.albumArtistName, "Album Artist")
        XCTAssertEqual(queue[1].track.genres, ["Electronic", "Test"])
    }

    func testRefreshDownloadStateRemovesCurrentLocalPathAndRestampsQualityWithoutEviction() async {
        let controller = makeController()
        var queue = [
            QueueItem(
                track: makeTrack(id: "current", localFilePath: "/downloads/current.mp3"),
                streamingQuality: nil
            ),
            QueueItem(
                track: makeTrack(id: "next", localFilePath: "/downloads/next.mp3"),
                streamingQuality: nil
            ),
        ]

        let result = await controller.refreshDownloadState(
            queue: &queue,
            currentQueueIndex: 0,
            fallbackStreamingQuality: "low",
            localFilePathForTrack: { track in
                track.id == "current" ? nil : track.localFilePath
            }
        )

        XCTAssertEqual(result.changedTrackIds, [queue[0].track.playbackIdentity])
        XCTAssertTrue(result.nonCurrentTrackIdsNeedingCacheEviction.isEmpty)
        XCTAssertNil(queue[0].track.localFilePath)
        XCTAssertEqual(queue[0].streamingQuality, "low")
        XCTAssertEqual(queue[1].track.localFilePath, "/downloads/next.mp3")
        XCTAssertNil(queue[1].streamingQuality)
    }

    private func makeController() -> PlaybackQueueController {
        PlaybackQueueController(
            queueStore: PlaybackQueueStore(defaults: .standard),
            maxHistorySize: 100
        )
    }

    private func makeTrack(
        id: String,
        localFilePath: String? = nil,
        sourceCompositeKey: String? = "plex:account:server:library"
    ) -> Track {
        Track(
            id: id,
            key: "/library/metadata/\(id)",
            title: "Track \(id)",
            artistName: "Artist",
            albumArtistName: "Album Artist",
            localFilePath: localFilePath,
            genres: ["Electronic", "Test"],
            sourceCompositeKey: sourceCompositeKey
        )
    }
}
