import XCTest
@testable import EnsembleCore

final class PlaybackQueueControllerTests: XCTestCase {
    func testAutoGeneratedIdentityPrefersQueueItemSource() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "manual"), source: .continuePlaying),
            QueueItem(track: makeTrack(id: "autoplay"), source: .autoplay)
        ]

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "autoplay", queue: queue))
        XCTAssertFalse(controller.isTrackAutoGenerated(id: "manual", queue: queue))
    }

    func testAutoGeneratedIdentityFallsBackToLegacyTrackedIds() {
        let controller = makeController()
        let queue = [
            QueueItem(track: makeTrack(id: "legacy"), source: .continuePlaying)
        ]

        controller.markAutoGeneratedTrack(id: "legacy")

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "legacy", queue: queue))
    }

    func testAutoGeneratedTrackingCanClearReplaceAndSyncFromQueue() {
        let controller = makeController()
        controller.replaceAutoGeneratedTrackIds(with: ["radio-seed", "stale"])

        XCTAssertTrue(controller.isTrackAutoGenerated(id: "radio-seed", queue: []))
        XCTAssertTrue(controller.removeAutoGeneratedTrack(id: "stale"))
        XCTAssertFalse(controller.isTrackAutoGenerated(id: "stale", queue: []))

        let queue = [
            QueueItem(track: makeTrack(id: "manual"), source: .continuePlaying),
            QueueItem(track: makeTrack(id: "restored-auto"), source: .autoplay)
        ]
        controller.syncAutoGeneratedTrackIds(from: queue)

        XCTAssertFalse(controller.isTrackAutoGenerated(id: "radio-seed", queue: []))
        XCTAssertTrue(controller.isTrackAutoGenerated(id: "restored-auto", queue: []))

        controller.clearAutoGeneratedTrackIds()

        XCTAssertFalse(controller.isTrackAutoGenerated(id: "restored-auto", queue: []))
    }

    private func makeController() -> PlaybackQueueController {
        PlaybackQueueController(
            queueStore: PlaybackQueueStore(defaults: .standard),
            maxHistorySize: 100
        )
    }

    private func makeTrack(id: String) -> Track {
        Track(
            id: id,
            key: "/library/metadata/\(id)",
            title: "Track \(id)",
            artistName: "Artist",
            sourceCompositeKey: "plex:account:server:library"
        )
    }
}
