import EnsembleCore
import SwiftUI

public struct TrackRow: View {
    let track: Track
    let showArtwork: Bool
    let showTrackNumber: Bool
    let isPlaying: Bool
    let isAutoGenerated: Bool
    let onTap: () -> Void
    let onPlayNext: (() -> Void)?
    let onPlayLast: (() -> Void)?
    let onAddToPlaylist: (() -> Void)?
    let onAddToRecentPlaylist: (() -> Void)?
    let onToggleFavorite: (() -> Void)?
    let onGoToAlbum: (() -> Void)?
    let onGoToArtist: (() -> Void)?
    let isFavorited: Bool?
    let recentPlaylistTitle: String?
    @Environment(\.dependencies) private var deps

    public init(
        track: Track,
        showArtwork: Bool = true,
        showTrackNumber: Bool = false,
        isPlaying: Bool = false,
        isAutoGenerated: Bool = false,
        onPlayNext: (() -> Void)? = nil,
        onPlayLast: (() -> Void)? = nil,
        onAddToPlaylist: (() -> Void)? = nil,
        onAddToRecentPlaylist: (() -> Void)? = nil,
        onToggleFavorite: (() -> Void)? = nil,
        onGoToAlbum: (() -> Void)? = nil,
        onGoToArtist: (() -> Void)? = nil,
        isFavorited: Bool? = nil,
        recentPlaylistTitle: String? = nil,
        onTap: @escaping () -> Void
    ) {
        self.track = track
        self.showArtwork = showArtwork
        self.showTrackNumber = showTrackNumber
        self.isPlaying = isPlaying
        self.isAutoGenerated = isAutoGenerated
        self.onPlayNext = onPlayNext
        self.onPlayLast = onPlayLast
        self.onAddToPlaylist = onAddToPlaylist
        self.onAddToRecentPlaylist = onAddToRecentPlaylist
        self.onToggleFavorite = onToggleFavorite
        self.onGoToAlbum = onGoToAlbum
        self.onGoToArtist = onGoToArtist
        self.isFavorited = isFavorited
        self.recentPlaylistTitle = recentPlaylistTitle
        self.onTap = onTap
    }

    public var body: some View {
        Button(action: handleTap) {
            HStack(spacing: 12) {
                if showTrackNumber {
                    trackNumberView
                        .frame(width: 30)
                }

                if showArtwork {
                    ArtworkView(track: track, size: .tiny, cornerRadius: 4)
                }

                VStack(alignment: .leading, spacing: 2) {
                    HStack(spacing: 6) {
                        Text(track.title)
                            .font(.body)
                            .foregroundColor(isPlaying ? .accentColor : (isAutoGenerated ? .purple : .primary))
                            .lineLimit(1)
                        
                        if isAutoGenerated {
                            Image(systemName: "sparkles")
                                .font(.caption2)
                                .foregroundColor(.purple)
                        }
                    }

                    if let artist = track.artistName {
                        Text(artist)
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                            .lineLimit(1)
                    }
                }

                Spacer()

                if track.isDownloaded {
                    Image(systemName: "arrow.down.circle.fill")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Text(track.formattedDuration)
                    .font(.subheadline)
                    .foregroundColor(.secondary)
                    .monospacedDigit()
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .contentShape(Rectangle())
        }
        .opacity(isUnavailableOffline ? 0.45 : 1)
        .buttonStyle(.plain)
        .transition(isAutoGenerated ? .opacity : .identity)
        .contextMenu {
            Section {
                if let onPlayNext = onPlayNext {
                    Button(action: onPlayNext) {
                        Label("Play Next", systemImage: "text.insert")
                    }
                }
                if let onPlayLast = onPlayLast {
                    Button(action: onPlayLast) {
                        Label("Play Last", systemImage: "text.append")
                    }
                }
            }

            Section {
                if let onGoToAlbum = onGoToAlbum, track.albumRatingKey != nil {
                    Button(action: onGoToAlbum) {
                        Label("Go to Album", systemImage: "square.stack")
                    }
                }
                if let onGoToArtist = onGoToArtist, track.artistRatingKey != nil {
                    Button(action: onGoToArtist) {
                        Label("Go to Artist", systemImage: "person.circle")
                    }
                }
            }

            Section {
                if let onAddToRecentPlaylist = onAddToRecentPlaylist,
                   let recentPlaylistTitle {
                    Button(action: onAddToRecentPlaylist) {
                        Label("Add to \(recentPlaylistTitle)", systemImage: "clock.arrow.circlepath")
                    }
                }
                if let onAddToPlaylist = onAddToPlaylist {
                    Button(action: onAddToPlaylist) {
                        Label("Add to Playlist…", systemImage: "text.badge.plus")
                    }
                }
                if let onToggleFavorite = onToggleFavorite {
                    Button(action: onToggleFavorite) {
                        if effectiveIsFavorited {
                            Label("Unfavorite", systemImage: "heart.slash")
                        } else {
                            Label("Favorite", systemImage: "heart")
                        }
                    }
                }
            }
        }
    }

    /// Track availability resolved from device connectivity, per-server health, and download state.
    private var trackAvailability: TrackAvailability {
        deps.trackAvailabilityResolver.availability(for: track)
    }

    private var isUnavailableOffline: Bool {
        trackAvailability.shouldDim
    }

    private func handleTap() {
        let availability = trackAvailability
        guard availability.canPlay else {
            deps.toastCenter.show(
                ToastPayload(
                    style: .warning,
                    iconSystemName: "wifi.slash",
                    title: availability.userMessage ?? "Not available offline",
                    message: "Download this track before going offline.",
                    dedupeKey: "offline-track-blocked-\(track.id)"
                )
            )
            return
        }
        onTap()
    }

    private var effectiveIsFavorited: Bool {
        isFavorited ?? (track.rating >= 8)
    }

    @ViewBuilder
    private var trackNumberView: some View {
        if isPlaying {
            Image(systemName: "speaker.wave.2.fill")
                .font(.caption)
                .foregroundColor(.accentColor)
        } else {
            Text("\(track.trackNumber)")
                .font(.subheadline)
                .foregroundColor(.secondary)
                .monospacedDigit()
        }
    }
}

// MARK: - Track List

public struct TrackListView: View {
    let tracks: [Track]
    let showArtwork: Bool
    let showTrackNumbers: Bool
    let currentTrackId: String?
    let autoGeneratedTrackIds: Set<String>
    let onTrackTap: (Track, Int) -> Void
    let onPlayNext: ((Track) -> Void)?
    let onPlayLast: ((Track) -> Void)?
    let onAddToPlaylist: ((Track) -> Void)?
    let onAddToRecentPlaylist: ((Track) -> Void)?
    let onToggleFavorite: ((Track) -> Void)?
    let onGoToAlbum: ((Track) -> Void)?
    let onGoToArtist: ((Track) -> Void)?
    let canAddToRecentPlaylist: ((Track) -> Bool)?
    let recentPlaylistTitle: String?
    let nowPlayingVM: NowPlayingViewModel?

    public init(
        tracks: [Track],
        showArtwork: Bool = true,
        showTrackNumbers: Bool = false,
        currentTrackId: String? = nil,
        autoGeneratedTrackIds: Set<String> = [],
        onPlayNext: ((Track) -> Void)? = nil,
        onPlayLast: ((Track) -> Void)? = nil,
        onAddToPlaylist: ((Track) -> Void)? = nil,
        onAddToRecentPlaylist: ((Track) -> Void)? = nil,
        onToggleFavorite: ((Track) -> Void)? = nil,
        onGoToAlbum: ((Track) -> Void)? = nil,
        onGoToArtist: ((Track) -> Void)? = nil,
        canAddToRecentPlaylist: ((Track) -> Bool)? = nil,
        recentPlaylistTitle: String? = nil,
        nowPlayingVM: NowPlayingViewModel? = nil,
        onTrackTap: @escaping (Track, Int) -> Void
    ) {
        self.tracks = tracks
        self.showArtwork = showArtwork
        self.showTrackNumbers = showTrackNumbers
        self.currentTrackId = currentTrackId
        self.autoGeneratedTrackIds = autoGeneratedTrackIds
        self.onPlayNext = onPlayNext
        self.onPlayLast = onPlayLast
        self.onAddToPlaylist = onAddToPlaylist
        self.onAddToRecentPlaylist = onAddToRecentPlaylist
        self.onToggleFavorite = onToggleFavorite
        self.onGoToAlbum = onGoToAlbum
        self.onGoToArtist = onGoToArtist
        self.canAddToRecentPlaylist = canAddToRecentPlaylist
        self.recentPlaylistTitle = recentPlaylistTitle
        self.nowPlayingVM = nowPlayingVM
        self.onTrackTap = onTrackTap
    }

    public var body: some View {
        LazyVStack(spacing: 0) {
            ForEach(Array(tracks.enumerated()), id: \.element.id) { index, track in
                let row = TrackRow(
                    track: track,
                    showArtwork: showArtwork,
                    showTrackNumber: showTrackNumbers,
                    isPlaying: track.id == currentTrackId,
                    isAutoGenerated: autoGeneratedTrackIds.contains(track.id),
                    onPlayNext: onPlayNext != nil ? { onPlayNext?(track) } : nil,
                    onPlayLast: onPlayLast != nil ? { onPlayLast?(track) } : nil,
                    onAddToPlaylist: onAddToPlaylist != nil ? { onAddToPlaylist?(track) } : nil,
                    onAddToRecentPlaylist: onAddToRecentPlaylist != nil && (canAddToRecentPlaylist?(track) ?? true) ? { onAddToRecentPlaylist?(track) } : nil,
                    onToggleFavorite: onToggleFavorite != nil ? { onToggleFavorite?(track) } : nil,
                    onGoToAlbum: onGoToAlbum != nil ? { onGoToAlbum?(track) } : nil,
                    onGoToArtist: onGoToArtist != nil ? { onGoToArtist?(track) } : nil,
                    isFavorited: nowPlayingVM?.isTrackFavorited(track),
                    recentPlaylistTitle: recentPlaylistTitle
                ) {
                    onTrackTap(track, index)
                }

                Group {
                    if let nowPlayingVM {
                        TrackSwipeContainer(
                            track: track,
                            nowPlayingVM: nowPlayingVM,
                            onPlayNext: onPlayNext != nil ? { onPlayNext?(track) } : nil,
                            onPlayLast: onPlayLast != nil ? { onPlayLast?(track) } : nil,
                            onAddToPlaylist: onAddToPlaylist != nil ? { onAddToPlaylist?(track) } : nil
                        ) {
                            row
                        }
                    } else {
                        row
                    }
                }
                .padding(.horizontal)
                .padding(.vertical, 8)

                if index < tracks.count - 1 {
                    Divider()
                        .padding(.leading, showArtwork ? 68 : (showTrackNumbers ? 54 : 16))
                }
            }
        }
    }
}
