import EnsembleCore
import SwiftUI

public struct TrackRow: View {
    let track: Track
    let showArtwork: Bool
    let showTrackNumber: Bool
    let isPlaying: Bool
    let isAutoGenerated: Bool
    let onTap: () -> Void
    let onPlayNext: (() -> Void)?
    let onPlayLast: (() -> Void)?
    let onAddToPlaylist: (() -> Void)?
    let onAddToRecentPlaylist: (() -> Void)?
    let onToggleFavorite: (() -> Void)?
    let onGoToAlbum: (() -> Void)?
    let onGoToArtist: (() -> Void)?
    let onShareLink: (() -> Void)?
    let onShareFile: (() -> Void)?
    let isFavorited: Bool?
    let recentPlaylistTitle: String?
    @Environment(\.dependencies) private var deps
    @State private var isEditingMetadata = false
    @State private var isConfirmingDelete = false
    /// Cached per-track availability — only updated when this track's availability actually
    /// changes, instead of re-rendering all visible rows on every generation bump.
    @State private var cachedAvailability: TrackAvailability = .available

    public init(
        track: Track,
        showArtwork: Bool = true,
        showTrackNumber: Bool = false,
        isPlaying: Bool = false,
        isAutoGenerated: Bool = false,
        onPlayNext: (() -> Void)? = nil,
        onPlayLast: (() -> Void)? = nil,
        onAddToPlaylist: (() -> Void)? = nil,
        onAddToRecentPlaylist: (() -> Void)? = nil,
        onToggleFavorite: (() -> Void)? = nil,
        onGoToAlbum: (() -> Void)? = nil,
        onGoToArtist: (() -> Void)? = nil,
        onShareLink: (() -> Void)? = nil,
        onShareFile: (() -> Void)? = nil,
        isFavorited: Bool? = nil,
        recentPlaylistTitle: String? = nil,
        onTap: @escaping () -> Void
    ) {
        self.track = track
        self.showArtwork = showArtwork
        self.showTrackNumber = showTrackNumber
        self.isPlaying = isPlaying
        self.isAutoGenerated = isAutoGenerated
        self.onPlayNext = onPlayNext
        self.onPlayLast = onPlayLast
        self.onAddToPlaylist = onAddToPlaylist
        self.onAddToRecentPlaylist = onAddToRecentPlaylist
        self.onToggleFavorite = onToggleFavorite
        self.onGoToAlbum = onGoToAlbum
        self.onGoToArtist = onGoToArtist
        self.onShareLink = onShareLink
        self.onShareFile = onShareFile
        self.isFavorited = isFavorited
        self.recentPlaylistTitle = recentPlaylistTitle
        self.onTap = onTap
    }

    public var body: some View {
        HStack(spacing: TrackListLayoutMetrics.rowInterItemSpacing) {
            Button(action: handleTap) {
                rowContentView
                    .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
            .frame(maxWidth: .infinity, alignment: .leading)

            if showsOverflowMenuButton {
                overflowMenuButton
            }
        }
        .contentShape(Rectangle())
        .opacity(isUnavailableOffline ? 0.45 : 1)
        .transition(isAutoGenerated ? .opacity : .identity)
        .contextMenu { contextMenuItems }
        .keyboardSafeEditorPresentation(isPresented: $isEditingMetadata) {
            MetadataEditSheet(kind: .track, currentTitle: track.title) { newTitle in
                do {
                    try await deps.metadataMutationService.editTrack(
                        track,
                        request: MetadataEditRequest(title: newTitle)
                    )
                    await MainActor.run {
                        deps.toastCenter.show(
                            ToastPayload(
                                style: .success,
                                iconSystemName: "checkmark.circle.fill",
                                title: "Track updated",
                                message: "\"\(newTitle)\" was saved to Plex.",
                                dedupeKey: "track-edit-\(track.id)"
                            )
                        )
                    }
                } catch {
                    await MainActor.run {
                        deps.toastCenter.show(
                            ToastPayload(
                                style: .error,
                                iconSystemName: "exclamationmark.triangle.fill",
                                title: "Couldn't edit track",
                                message: error.localizedDescription,
                                dedupeKey: "track-edit-failed-\(track.id)"
                            )
                        )
                    }
                    throw error
                }
            }
        }
        .confirmationDialog(
            "Delete Track?",
            isPresented: $isConfirmingDelete,
            titleVisibility: .visible
        ) {
            Button("Delete Track", role: .destructive) {
                Task {
                    do {
                        try await deps.metadataMutationService.deleteTrack(track)
                        await MainActor.run {
                            deps.toastCenter.show(
                                ToastPayload(
                                    style: .success,
                                    iconSystemName: "trash.fill",
                                    title: "Track deleted",
                                    message: "\"\(track.title)\" was removed from Plex.",
                                    dedupeKey: "track-delete-\(track.id)"
                                )
                            )
                        }
                    } catch {
                        await MainActor.run {
                            deps.toastCenter.show(
                                ToastPayload(
                                    style: .error,
                                    iconSystemName: "exclamationmark.triangle.fill",
                                    title: "Couldn't delete track",
                                    message: error.localizedDescription,
                                    dedupeKey: "track-delete-failed-\(track.id)"
                                )
                            )
                        }
                    }
                }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("This permanently deletes \"\(track.title)\" from the Plex server and removes its local cache.")
        }
        #if os(iOS)
        // Drag and drop for downloaded tracks on iPad (Split View / Stage Manager)
        .if(track.localFilePath != nil) { view in
            view.onDrag {
                guard let path = track.localFilePath else { return NSItemProvider() }
                let fileURL = URL(fileURLWithPath: path)
                let provider = NSItemProvider(contentsOf: fileURL) ?? NSItemProvider()
                if let artist = track.artistName {
                    provider.suggestedName = "\(artist) - \(track.title)"
                } else {
                    provider.suggestedName = track.title
                }
                return provider
            }
        }
        #endif
        // Update cached availability when generation bumps (network/server/download change).
        // Only assigns @State (triggering re-render) when this track's availability actually changed.
        .onReceive(DependencyContainer.shared.trackAvailabilityResolver.$availabilityGeneration) { _ in
            let resolver = DependencyContainer.shared.trackAvailabilityResolver
            let newAvailability = resolver.availability(for: track)
            if newAvailability != cachedAvailability {
                cachedAvailability = newAvailability
            }
        }
        .onAppear {
            cachedAvailability = DependencyContainer.shared.trackAvailabilityResolver.availability(for: track)
        }
    }

    // MARK: - Extracted Row Content

    /// The row's visual content, extracted so it can be reused as the context menu preview
    @ViewBuilder
    private var rowContentView: some View {
        HStack(spacing: TrackListLayoutMetrics.rowInterItemSpacing) {
            if showTrackNumber {
                trackNumberView
                    .frame(width: 30)
            }

            if showArtwork {
                ArtworkView(track: track, size: .tiny, cornerRadius: ArtworkCornerRadius.square(for: .tiny))
            }

            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(track.title)
                        .font(.body)
                        .foregroundColor(isPlaying ? .accentColor : (isAutoGenerated ? .purple : .primary))
                        .lineLimit(1)

                    if isAutoGenerated {
                        Image(systemName: "sparkles")
                            .font(.caption2)
                            .foregroundColor(.purple)
                    }
                }

                if let artist = track.artistName {
                    Text(artist)
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                        .lineLimit(1)
                }
            }

            Spacer()

            // Download status: spinner while queued/downloading, icon when complete
            if isActivelyDownloading {
                ProgressView()
                    .scaleEffect(0.7)
                    .frame(width: 16, height: 16)
            } else if track.isDownloaded {
                Image(systemName: "arrow.down.circle.fill")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Text(track.formattedDuration)
                .font(.subheadline)
                .foregroundColor(.secondary)
                .monospacedDigit()
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        // Favorite heart centered between screen edge and first content element
        .overlay(alignment: .leading) {
            if effectiveIsFavorited {
                Image(systemName: "heart.fill")
                    .font(.caption)
                    .foregroundColor(.pink)
                    .offset(x: -8)
            }
        }
    }

    private var overflowMenuButton: some View {
        Menu {
            contextMenuItems
        } label: {
            Image(systemName: "ellipsis")
                .font(.body.weight(.semibold))
                .foregroundColor(.secondary)
                .frame(width: 28, height: 28)
                .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Track Actions")
    }

    private var showsOverflowMenuButton: Bool {
        #if os(iOS)
        true
        #else
        false
        #endif
    }

    // MARK: - Context Menu Items

    @ViewBuilder
    private var contextMenuItems: some View {
        Section {
            if let onPlayNext = onPlayNext {
                Button(action: onPlayNext) {
                    Label("Play Next", systemImage: "text.insert")
                }
            }
            if let onPlayLast = onPlayLast {
                Button(action: onPlayLast) {
                    Label("Play Last", systemImage: "text.append")
                }
            }
        }

        Section {
            Button {
                // Context-menu initiated editor presentation can be swallowed
                // when triggered before the menu dismiss animation completes.
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) {
                    DispatchQueue.main.async {
                        isEditingMetadata = true
                    }
                }
            } label: {
                Label("Edit Metadata…", systemImage: "pencil")
            }

            if let onGoToAlbum = onGoToAlbum, track.albumRatingKey != nil {
                Button(action: onGoToAlbum) {
                    Label("Go to Album", systemImage: "square.stack")
                }
            }
            if let onGoToArtist = onGoToArtist, track.artistRatingKey != nil {
                Button(action: onGoToArtist) {
                    Label("Go to Artist", systemImage: "person.circle")
                }
            }
        }

        Section {
            if let onAddToRecentPlaylist = onAddToRecentPlaylist,
               let recentPlaylistTitle {
                Button(action: onAddToRecentPlaylist) {
                    Label("Add to \(recentPlaylistTitle)", systemImage: "clock.arrow.circlepath")
                }
            }
            if let onAddToPlaylist = onAddToPlaylist {
                Button(action: onAddToPlaylist) {
                    Label("Add to Playlist…", systemImage: "text.badge.plus")
                }
            }
            if let onToggleFavorite = onToggleFavorite {
                Button(action: onToggleFavorite) {
                    if effectiveIsFavorited {
                        Label("Unfavorite", systemImage: "heart.slash")
                    } else {
                        Label("Favorite", systemImage: "heart")
                    }
                }
            }
        }

        // Share actions
        if onShareLink != nil || onShareFile != nil {
            Section {
                if let onShareLink = onShareLink {
                    Button(action: onShareLink) {
                        Label("Share Link…", systemImage: "link")
                    }
                }
                if let onShareFile = onShareFile {
                    Button(action: onShareFile) {
                        Label("Share Audio File…", systemImage: "square.and.arrow.up")
                    }
                }
            }
        }

        Section {
            Button(role: .destructive) {
                isConfirmingDelete = true
            } label: {
                Label("Delete Track", systemImage: "trash")
            }
        }
    }

    /// Whether this track is currently queued or actively downloading.
    private var isActivelyDownloading: Bool {
        deps.offlineDownloadService.activeDownloadRatingKeys.contains(track.id)
    }

    private var isUnavailableOffline: Bool {
        cachedAvailability.shouldDim
    }

    private func handleTap() {
        let availability = cachedAvailability
        guard availability.canPlay else {
            deps.toastCenter.show(
                ToastPayload(
                    style: .warning,
                    iconSystemName: "wifi.slash",
                    title: availability.userMessage ?? "Not available offline",
                    message: "Download this track before going offline.",
                    dedupeKey: "offline-track-blocked-\(track.id)"
                )
            )
            return
        }
        onTap()
    }

    private var effectiveIsFavorited: Bool {
        isFavorited ?? (track.rating >= 8)
    }

    @ViewBuilder
    private var trackNumberView: some View {
        if isPlaying {
            Image(systemName: "speaker.wave.2.fill")
                .font(.caption)
                .foregroundColor(.accentColor)
        } else {
            Text("\(track.trackNumber)")
                .font(.subheadline)
                .foregroundColor(.secondary)
                .monospacedDigit()
        }
    }
}

// MARK: - Track List

public struct TrackListView: View {
    let tracks: [Track]
    let showArtwork: Bool
    let showTrackNumbers: Bool
    let currentTrackId: String?
    let autoGeneratedTrackIds: Set<String>
    let onTrackTap: (Track, Int) -> Void
    let onPlayNext: ((Track) -> Void)?
    let onPlayLast: ((Track) -> Void)?
    let onAddToPlaylist: ((Track) -> Void)?
    let onAddToRecentPlaylist: ((Track) -> Void)?
    let onToggleFavorite: ((Track) -> Void)?
    let onGoToAlbum: ((Track) -> Void)?
    let onGoToArtist: ((Track) -> Void)?
    let onShareLink: ((Track) -> Void)?
    let onShareFile: ((Track) -> Void)?
    let canAddToRecentPlaylist: ((Track) -> Bool)?
    let recentPlaylistTitle: String?
    let nowPlayingVM: NowPlayingViewModel?
    private let interactionModel: TrackRowInteractionModel

    public init(
        tracks: [Track],
        showArtwork: Bool = true,
        showTrackNumbers: Bool = false,
        currentTrackId: String? = nil,
        autoGeneratedTrackIds: Set<String> = [],
        onPlayNext: ((Track) -> Void)? = nil,
        onPlayLast: ((Track) -> Void)? = nil,
        onAddToPlaylist: ((Track) -> Void)? = nil,
        onAddToRecentPlaylist: ((Track) -> Void)? = nil,
        onToggleFavorite: ((Track) -> Void)? = nil,
        onGoToAlbum: ((Track) -> Void)? = nil,
        onGoToArtist: ((Track) -> Void)? = nil,
        onShareLink: ((Track) -> Void)? = nil,
        onShareFile: ((Track) -> Void)? = nil,
        canAddToRecentPlaylist: ((Track) -> Bool)? = nil,
        recentPlaylistTitle: String? = nil,
        nowPlayingVM: NowPlayingViewModel? = nil,
        onTrackTap: @escaping (Track, Int) -> Void
    ) {
        self.tracks = tracks
        self.showArtwork = showArtwork
        self.showTrackNumbers = showTrackNumbers
        self.currentTrackId = currentTrackId
        self.autoGeneratedTrackIds = autoGeneratedTrackIds
        self.onPlayNext = onPlayNext
        self.onPlayLast = onPlayLast
        self.onAddToPlaylist = onAddToPlaylist
        self.onAddToRecentPlaylist = onAddToRecentPlaylist
        self.onToggleFavorite = onToggleFavorite
        self.onGoToAlbum = onGoToAlbum
        self.onGoToArtist = onGoToArtist
        self.onShareLink = onShareLink
        self.onShareFile = onShareFile
        self.canAddToRecentPlaylist = canAddToRecentPlaylist
        self.recentPlaylistTitle = recentPlaylistTitle
        self.nowPlayingVM = nowPlayingVM
        self.onTrackTap = onTrackTap
        self.interactionModel = TrackRowInteractionModel(
            onPlayNext: onPlayNext,
            onPlayLast: onPlayLast,
            onAddToPlaylist: onAddToPlaylist,
            onAddToRecentPlaylist: onAddToRecentPlaylist,
            onToggleFavorite: onToggleFavorite,
            onGoToAlbum: onGoToAlbum,
            onGoToArtist: onGoToArtist,
            onShareLink: onShareLink,
            onShareFile: onShareFile,
            isTrackFavorited: nowPlayingVM.map { viewModel in { viewModel.isTrackFavorited($0) } },
            canAddToRecentPlaylist: canAddToRecentPlaylist,
            recentPlaylistTitle: recentPlaylistTitle
        )
    }

    public var body: some View {
        LazyVStack(spacing: 0) {
            ForEach(Array(tracks.enumerated()), id: \.element.id) { index, track in
                let resolvedActions = interactionModel.resolve(for: track)
                let row = TrackRow(
                    track: track,
                    showArtwork: showArtwork,
                    showTrackNumber: showTrackNumbers,
                    isPlaying: track.id == currentTrackId,
                    isAutoGenerated: autoGeneratedTrackIds.contains(track.id),
                    onPlayNext: resolvedActions.onPlayNext,
                    onPlayLast: resolvedActions.onPlayLast,
                    onAddToPlaylist: resolvedActions.onAddToPlaylist,
                    onAddToRecentPlaylist: resolvedActions.onAddToRecentPlaylist,
                    onToggleFavorite: resolvedActions.onToggleFavorite,
                    onGoToAlbum: resolvedActions.onGoToAlbum,
                    onGoToArtist: resolvedActions.onGoToArtist,
                    onShareLink: resolvedActions.onShareLink,
                    onShareFile: resolvedActions.onShareFile,
                    isFavorited: resolvedActions.isFavorited,
                    recentPlaylistTitle: resolvedActions.recentPlaylistTitle
                ) {
                    onTrackTap(track, index)
                }

                Group {
                    if let nowPlayingVM {
                        TrackSwipeContainer(
                            track: track,
                            nowPlayingVM: nowPlayingVM,
                            onPlayNext: resolvedActions.onPlayNext,
                            onPlayLast: resolvedActions.onPlayLast,
                            onAddToPlaylist: resolvedActions.onAddToPlaylist
                        ) {
                            row
                        }
                    } else {
                        row
                    }
                }
                .padding(.horizontal, TrackListLayoutMetrics.rowHorizontalPadding)
                .padding(.vertical, TrackListLayoutMetrics.rowVerticalPadding)

                if index < tracks.count - 1 {
                    Divider()
                        .padding(
                            .leading,
                            TrackListLayoutMetrics.contentLeadingInset(
                                showArtwork: showArtwork,
                                showTrackNumbers: showTrackNumbers
                            )
                        )
                }
            }
        }
    }
}
