import EnsembleDomain

typealias WatchCompanionPlaybackState = EnsembleCompanionPlaybackState
typealias WatchCompanionRepeatMode = EnsembleCompanionRepeatMode
typealias WatchCompanionTrackSnapshot = EnsembleCompanionTrackSnapshot
typealias WatchCompanionPlaylistTargetSnapshot = EnsembleCompanionPlaylistTargetSnapshot
typealias WatchCompanionSessionSnapshot = EnsembleCompanionSessionSnapshot
typealias WatchCompanionQueueItemSnapshot = EnsembleCompanionQueueItemSnapshot
typealias WatchCompanionQueueSnapshot = EnsembleCompanionQueueSnapshot
typealias WatchCompanionTrackPayload = EnsembleCompanionTrackPayload
typealias WatchCompanionCommandKind = EnsembleCompanionCommandKind
typealias WatchCompanionCommand = EnsembleCompanionCommand
typealias WatchCompanionCommandResponse = EnsembleCompanionCommandResponse
typealias WatchCompanionPayloadKey = EnsembleCompanionPayloadKey
